# Do not Edit this file, TimeVortex uses it to store data

TimeVortexDrive1 = 100.0
TimeVortexDrive2 = 0.0
TimeVortexDrive3 = 0.0
TimeVortexDrive4 = 0.0
TimeVortexDrive5 = 0.0
TimeVortexDrive6 = 0.0
TimeVortexDrive7 = 0.0
TimeVortexDrive8 = 0.0
TimeVortexDrive9 = 0.0
TimeVortexDrive10 = 0.0
TimeVortexDrive11 = 0.0
TimeVortexDrive12 = 0.0
TimeVortexDrive13 = 0.0
TimeVortexDrive14 = 0.0
TimeVortexDrive15 = 0.0
TimeVortexDrive16 = 0.0
TimeVortexDrive17 = 0.0
TimeVortexDrive18 = 0.0
TimeVortexDrive19 = 0.0
TimeVortexDrive20 = 0.0