# Do not Edit this file, Slipstream uses it to store data

SlipstreamDrive1 = 100.0
SlipstreamDrive2 = 0.0
SlipstreamDrive3 = 0.0
SlipstreamDrive4 = 0.0
SlipstreamDrive5 = 0.0
SlipstreamDrive6 = 0.0
SlipstreamDrive7 = 0.0
SlipstreamDrive8 = 0.0
SlipstreamDrive9 = 0.0
SlipstreamDrive10 = 0.0
SlipstreamDrive11 = 0.0
SlipstreamDrive12 = 0.0
SlipstreamDrive13 = 0.0
SlipstreamDrive14 = 0.0
SlipstreamDrive15 = 0.0
SlipstreamDrive16 = 0.0
SlipstreamDrive17 = 0.0
SlipstreamDrive18 = 0.0
SlipstreamDrive19 = 0.0
SlipstreamDrive20 = 0.0