# Carrier file Borg cube.py autogenerated by http://defiant.homedns.org/~erik/STBC/carrier/

Carrier = __import__("ftb.Carrier")
class BorgCube(Carrier.Carrier):
    def __init__(self, pShip):
        Carrier.Carrier.__init__(self, pShip)
        LauncherGroup = __import__("ftb.LauncherGroup")
        group = LauncherGroup.LauncherGroup()

        LauncherManager = __import__("ftb.LauncherManager")

	launcher1 = LauncherManager.GetLauncher("Sphere Launcher", pShip)
	group.AddLauncher("Sphere Launcher", launcher1)

	launcher1.AddLaunchable("sphere", "ftb.enemyAI", 1)

	self.AddLauncher("Group 1", group)

ShipManager = __import__("ftb.ShipManager")
ShipManager.RegisterShipClass("Borg Cube", BorgCube)
