#####  Created by:
#####  Tactical Display Icon Editor



import App
import GlobalPropertyTemplates

# Local Templates
#################################################
kAftTorpedo1 = App.TorpedoTubeProperty_Create("Aft Torpedo 1")

kAftTorpedo1.SetMaxCondition(125000.0)
kAftTorpedo1.SetCritical(0)
kAftTorpedo1.SetTargetable(1)
kAftTorpedo1.SetPrimary(1)
kAftTorpedo1.SetPosition(-0.04, -1.26, 0.015)
kAftTorpedo1.SetPosition2D(4.0, 5.0)
kAftTorpedo1.SetRepairComplexity(3.0)
kAftTorpedo1.SetDisabledPercentage(0.25)
kAftTorpedo1.SetRadius(0.01)
kAftTorpedo1.SetDumbfire(1)
kAftTorpedo1.SetWeaponID(2)
kAftTorpedo1.SetGroups(20)
kAftTorpedo1.SetDamageRadiusFactor(0.2)
kAftTorpedo1.SetIconNum(370)
kAftTorpedo1.SetIconPositionX(72.000000)
kAftTorpedo1.SetIconPositionY(127.000000)
kAftTorpedo1.SetIconAboveShip(1)
kAftTorpedo1.SetImmediateDelay(0.5)
kAftTorpedo1.SetReloadDelay(30.0)
kAftTorpedo1.SetMaxReady(5)
kAftTorpedo1Direction = App.TGPoint3()
kAftTorpedo1Direction.SetXYZ(0.0, -1.0, 0.0)
kAftTorpedo1.SetDirection(kAftTorpedo1Direction)
kAftTorpedo1Right = App.TGPoint3()
kAftTorpedo1Right.SetXYZ(-1.0, 0.0, 0.0)
kAftTorpedo1.SetRight(kAftTorpedo1Right)
App.g_kModelPropertyManager.RegisterLocalTemplate(kAftTorpedo1)
#################################################
kAftTorpedo2 = App.TorpedoTubeProperty_Create("Aft Torpedo 2")

kAftTorpedo2.SetMaxCondition(125000.0)
kAftTorpedo2.SetCritical(0)
kAftTorpedo2.SetTargetable(1)
kAftTorpedo2.SetPrimary(1)
kAftTorpedo2.SetPosition(0.04, -1.26, 0.015)
kAftTorpedo2.SetPosition2D(4.0, 5.0)
kAftTorpedo2.SetRepairComplexity(3.0)
kAftTorpedo2.SetDisabledPercentage(0.25)
kAftTorpedo2.SetRadius(0.01)
kAftTorpedo2.SetDumbfire(1)
kAftTorpedo2.SetWeaponID(2)
kAftTorpedo2.SetGroups(20)
kAftTorpedo2.SetDamageRadiusFactor(0.2)
kAftTorpedo2.SetIconNum(370)
kAftTorpedo2.SetIconPositionX(82.000000)
kAftTorpedo2.SetIconPositionY(127.000000)
kAftTorpedo2.SetIconAboveShip(1)
kAftTorpedo2.SetImmediateDelay(0.5)
kAftTorpedo2.SetReloadDelay(30.0)
kAftTorpedo2.SetMaxReady(5)
kAftTorpedo2Direction = App.TGPoint3()
kAftTorpedo2Direction.SetXYZ(0.0, -1.0, 0.0)
kAftTorpedo2.SetDirection(kAftTorpedo2Direction)
kAftTorpedo2Right = App.TGPoint3()
kAftTorpedo2Right.SetXYZ(1.0, 0.0, 0.0)
kAftTorpedo2.SetRight(kAftTorpedo2Right)
App.g_kModelPropertyManager.RegisterLocalTemplate(kAftTorpedo2)
#################################################
kAftTractor = App.TractorBeamProperty_Create("Aft Tractor")

kAftTractor.SetMaxCondition(95000.0)
kAftTractor.SetCritical(0)
kAftTractor.SetTargetable(1)
kAftTractor.SetPrimary(1)
kAftTractor.SetPosition(0.0, -1.35, 0.075)
kAftTractor.SetPosition2D(65.0, 71.0)
kAftTractor.SetRepairComplexity(5.0)
kAftTractor.SetDisabledPercentage(0.25)
kAftTractor.SetRadius(0.15)
kAftTractor.SetDumbfire(0)
kAftTractor.SetWeaponID(7)
kAftTractor.SetGroups(0)
kAftTractor.SetDamageRadiusFactor(0.3)
kAftTractor.SetIconNum(0)
kAftTractor.SetIconPositionX(0.0)
kAftTractor.SetIconPositionY(0.0)
kAftTractor.SetIconAboveShip(1)
kAftTractor.SetFireSound("Klingon Tractor")
kAftTractor.SetMaxCharge(5.0)
kAftTractor.SetMaxDamage(500.0)
kAftTractor.SetMaxDamageDistance(120.0)
kAftTractor.SetMinFiringCharge(3.0)
kAftTractor.SetNormalDischargeRate(1.0)
kAftTractor.SetRechargeRate(0.3)
kAftTractor.SetIndicatorIconNum(0)
kAftTractor.SetIndicatorIconPositionX(0.0)
kAftTractor.SetIndicatorIconPositionY(0.0)
kAftTractorForward = App.TGPoint3()
kAftTractorForward.SetXYZ(0.0, -1.0, 0.0)
kAftTractorUp = App.TGPoint3()
kAftTractorUp.SetXYZ(0.0, 0.0, 1.0)
kAftTractor.SetOrientation(kAftTractorForward, kAftTractorUp)
kAftTractor.SetArcWidthAngles(-1.22173, 1.22173)
kAftTractor.SetArcHeightAngles(-1.22173, 1.22173)
kAftTractor.SetTractorBeamWidth(0.3)
kAftTractor.SetTextureStart(0)
kAftTractor.SetTextureEnd(0)
kColor = App.TGColorA()
kColor.SetRGBA(0.4, 0.4, 1.0, 1.0)
kAftTractor.SetOuterShellColor(kColor)
kColor.SetRGBA(0.4, 0.4, 1.0, 1.0)
kAftTractor.SetInnerShellColor(kColor)
kColor.SetRGBA(0.4, 0.4, 1.0, 1.0)
kAftTractor.SetOuterCoreColor(kColor)
kColor.SetRGBA(0.4, 0.4, 1.0, 1.0)
kAftTractor.SetInnerCoreColor(kColor)
kAftTractor.SetNumSides(12)
kAftTractor.SetMainRadius(0.075)
kAftTractor.SetTaperRadius(0.0)
kAftTractor.SetCoreScale(0.45)
kAftTractor.SetTaperRatio(0.2)
kAftTractor.SetTaperMinLength(1.0)
kAftTractor.SetTaperMaxLength(5.0)
kAftTractor.SetLengthTextureTilePerUnit(0.25)
kAftTractor.SetPerimeterTile(1.0)
kAftTractor.SetTextureSpeed(0.2)
kAftTractor.SetTextureName("data/Textures/Tactical/TractorBeam.tga")
App.g_kModelPropertyManager.RegisterLocalTemplate(kAftTractor)
#################################################
kAndisiteAC = App.ShipProperty_Create("AndisiteAC")

kAndisiteAC.SetGenus(1)
kAndisiteAC.SetSpecies(407)
kAndisiteAC.SetMass(65000.0)
kAndisiteAC.SetRotationalInertia(650000.0)
kAndisiteAC.SetShipName("AndisiteAC")
kAndisiteAC.SetModelFilename("data/Models/Ships/AndisiteAC/AndisiteAC.nif")
kAndisiteAC.SetDamageResolution(10.0)
kAndisiteAC.SetAffiliation(0)
kAndisiteAC.SetStationary(0)
kAndisiteAC.SetAIString("NonFedAttack")
kAndisiteAC.SetDeathExplosionSound("g_lsDeathExplosions")
App.g_kModelPropertyManager.RegisterLocalTemplate(kAndisiteAC)
#################################################
kCrystalineCore = App.PowerProperty_Create("Crystaline Core")

kCrystalineCore.SetMaxCondition(395000.0)
kCrystalineCore.SetCritical(1)
kCrystalineCore.SetTargetable(1)
kCrystalineCore.SetPrimary(1)
kCrystalineCore.SetPosition(0.0, -0.65, 0.05)
kCrystalineCore.SetPosition2D(65.0, 57.0)
kCrystalineCore.SetRepairComplexity(2.0)
kCrystalineCore.SetDisabledPercentage(0.25)
kCrystalineCore.SetRadius(0.075)
kCrystalineCore.SetMainBatteryLimit(485000.0)
kCrystalineCore.SetBackupBatteryLimit(485000.0)
kCrystalineCore.SetMainConduitCapacity(10500.0)
kCrystalineCore.SetBackupConduitCapacity(7500.0)
kCrystalineCore.SetPowerOutput(10000.0)
App.g_kModelPropertyManager.RegisterLocalTemplate(kCrystalineCore)
#################################################
kElectronAft = App.PhaserProperty_Create("Electron Aft")

kElectronAft.SetMaxCondition(95000.0)
kElectronAft.SetCritical(0)
kElectronAft.SetTargetable(1)
kElectronAft.SetPrimary(1)
kElectronAft.SetPosition(0.0, -1.35, 0.08)
kElectronAft.SetPosition2D(65.0, 5.0)
kElectronAft.SetRepairComplexity(4.0)
kElectronAft.SetDisabledPercentage(0.125)
kElectronAft.SetRadius(0.25)
kElectronAft.SetDumbfire(0)
kElectronAft.SetWeaponID(1)
kElectronAft.SetGroups(0)
kElectronAft.SetDamageRadiusFactor(0.4)
kElectronAft.SetIconNum(363)
kElectronAft.SetIconPositionX(64.000000)
kElectronAft.SetIconPositionY(112.000000)
kElectronAft.SetIconAboveShip(1)
kElectronAft.SetFireSound("AndisiteElectron")
kElectronAft.SetMaxCharge(1.25)
kElectronAft.SetMaxDamage(85000.0)
kElectronAft.SetMaxDamageDistance(550.0)
kElectronAft.SetMinFiringCharge(1.0)
kElectronAft.SetNormalDischargeRate(1.25)
kElectronAft.SetRechargeRate(1.5)
kElectronAft.SetIndicatorIconNum(511)
kElectronAft.SetIndicatorIconPositionX(59.000000)
kElectronAft.SetIndicatorIconPositionY(107.000000)
kElectronAftForward = App.TGPoint3()
kElectronAftForward.SetXYZ(0.0, -1.0, 0.0)
kElectronAftUp = App.TGPoint3()
kElectronAftUp.SetXYZ(0.0, 0.0, 1.0)
kElectronAft.SetOrientation(kElectronAftForward, kElectronAftUp)
kElectronAft.SetWidth(0.001)
kElectronAft.SetLength(0.001)
kElectronAft.SetArcWidthAngles(-0.959931, 0.959931)
kElectronAft.SetArcHeightAngles(-0.959931, 0.959931)
kElectronAft.SetPhaserTextureStart(0)
kElectronAft.SetPhaserTextureEnd(0)
kElectronAft.SetPhaserWidth(0.3)
kColor = App.TGColorA()
kColor.SetRGBA(1.0, 1.0, 1.0, 1.0)
kElectronAft.SetOuterShellColor(kColor)
kColor.SetRGBA(1.0, 1.0, 1.0, 1.0)
kElectronAft.SetInnerShellColor(kColor)
kColor.SetRGBA(1.0, 1.0, 1.0, 1.0)
kElectronAft.SetOuterCoreColor(kColor)
kColor.SetRGBA(1.0, 1.0, 1.0, 1.0)
kElectronAft.SetInnerCoreColor(kColor)
kElectronAft.SetNumSides(6)
kElectronAft.SetMainRadius(0.05)
kElectronAft.SetTaperRadius(0.05)
kElectronAft.SetCoreScale(0.5)
kElectronAft.SetTaperRatio(0.25)
kElectronAft.SetTaperMinLength(5.0)
kElectronAft.SetTaperMaxLength(30.0)
kElectronAft.SetLengthTextureTilePerUnit(0.5)
kElectronAft.SetPerimeterTile(1.0)
kElectronAft.SetTextureSpeed(2.5)
kElectronAft.SetTextureName("data/JLSKrenim.tga")
App.g_kModelPropertyManager.RegisterLocalTemplate(kElectronAft)
#################################################
kElectronBeamCore = App.WeaponSystemProperty_Create("Electron Beam Core")

kElectronBeamCore.SetMaxCondition(275000.0)
kElectronBeamCore.SetCritical(0)
kElectronBeamCore.SetTargetable(1)
kElectronBeamCore.SetPrimary(1)
kElectronBeamCore.SetPosition(0.0, 0.2, -0.2)
kElectronBeamCore.SetPosition2D(3.0, 20.0)
kElectronBeamCore.SetRepairComplexity(3.0)
kElectronBeamCore.SetDisabledPercentage(0.25)
kElectronBeamCore.SetRadius(0.04)
kElectronBeamCore.SetNormalPowerPerSecond(50.0)
kElectronBeamCore.SetWeaponSystemType(kElectronBeamCore.WST_PHASER)
kElectronBeamCore.SetSingleFire(0)
kElectronBeamCore.SetAimedWeapon(0)
kFiringChainString = App.TGString()
kFiringChainString.SetString("")
kElectronBeamCore.SetFiringChainString(kFiringChainString)
App.g_kModelPropertyManager.RegisterLocalTemplate(kElectronBeamCore)
#################################################
kElectronFore1 = App.PhaserProperty_Create("Electron Fore 1")

kElectronFore1.SetMaxCondition(95000.0)
kElectronFore1.SetCritical(0)
kElectronFore1.SetTargetable(1)
kElectronFore1.SetPrimary(1)
kElectronFore1.SetPosition(0.7, -0.1, -0.1075)
kElectronFore1.SetPosition2D(65.0, 5.0)
kElectronFore1.SetRepairComplexity(4.0)
kElectronFore1.SetDisabledPercentage(0.125)
kElectronFore1.SetRadius(0.25)
kElectronFore1.SetDumbfire(0)
kElectronFore1.SetWeaponID(1)
kElectronFore1.SetGroups(0)
kElectronFore1.SetDamageRadiusFactor(0.4)
kElectronFore1.SetIconNum(350)
kElectronFore1.SetIconPositionX(93.000000)
kElectronFore1.SetIconPositionY(65.000000)
kElectronFore1.SetIconAboveShip(1)
kElectronFore1.SetFireSound("AndisiteElectron")
kElectronFore1.SetMaxCharge(1.25)
kElectronFore1.SetMaxDamage(85000.0)
kElectronFore1.SetMaxDamageDistance(550.0)
kElectronFore1.SetMinFiringCharge(1.0)
kElectronFore1.SetNormalDischargeRate(1.25)
kElectronFore1.SetRechargeRate(1.5)
kElectronFore1.SetIndicatorIconNum(510)
kElectronFore1.SetIndicatorIconPositionX(58.0)
kElectronFore1.SetIndicatorIconPositionY(31.0)
kElectronFore1Forward = App.TGPoint3()
kElectronFore1Forward.SetXYZ(0.0, 1.0, 0.0)
kElectronFore1Up = App.TGPoint3()
kElectronFore1Up.SetXYZ(0.0, 0.0, 1.0)
kElectronFore1.SetOrientation(kElectronFore1Forward, kElectronFore1Up)
kElectronFore1.SetWidth(0.001)
kElectronFore1.SetLength(0.001)
kElectronFore1.SetArcWidthAngles(-0.488692, 0.959931)
kElectronFore1.SetArcHeightAngles(-0.610865, 0.610865)
kElectronFore1.SetPhaserTextureStart(0)
kElectronFore1.SetPhaserTextureEnd(0)
kElectronFore1.SetPhaserWidth(0.3)
kColor = App.TGColorA()
kColor.SetRGBA(1.0, 1.0, 1.0, 1.0)
kElectronFore1.SetOuterShellColor(kColor)
kColor.SetRGBA(1.0, 1.0, 1.0, 1.0)
kElectronFore1.SetInnerShellColor(kColor)
kColor.SetRGBA(1.0, 1.0, 1.0, 1.0)
kElectronFore1.SetOuterCoreColor(kColor)
kColor.SetRGBA(1.0, 1.0, 1.0, 1.0)
kElectronFore1.SetInnerCoreColor(kColor)
kElectronFore1.SetNumSides(6)
kElectronFore1.SetMainRadius(0.05)
kElectronFore1.SetTaperRadius(0.05)
kElectronFore1.SetCoreScale(0.5)
kElectronFore1.SetTaperRatio(0.25)
kElectronFore1.SetTaperMinLength(5.0)
kElectronFore1.SetTaperMaxLength(30.0)
kElectronFore1.SetLengthTextureTilePerUnit(0.5)
kElectronFore1.SetPerimeterTile(1.0)
kElectronFore1.SetTextureSpeed(2.5)
kElectronFore1.SetTextureName("data/JLSKrenim.tga")
App.g_kModelPropertyManager.RegisterLocalTemplate(kElectronFore1)
#################################################
kElectronFore2 = App.PhaserProperty_Create("Electron Fore 2")

kElectronFore2.SetMaxCondition(95000.0)
kElectronFore2.SetCritical(0)
kElectronFore2.SetTargetable(1)
kElectronFore2.SetPrimary(1)
kElectronFore2.SetPosition(-0.7, -0.1, -0.1075)
kElectronFore2.SetPosition2D(65.0, 5.0)
kElectronFore2.SetRepairComplexity(4.0)
kElectronFore2.SetDisabledPercentage(0.125)
kElectronFore2.SetRadius(0.25)
kElectronFore2.SetDumbfire(0)
kElectronFore2.SetWeaponID(1)
kElectronFore2.SetGroups(0)
kElectronFore2.SetDamageRadiusFactor(0.4)
kElectronFore2.SetIconNum(330)
kElectronFore2.SetIconPositionX(12.000000)
kElectronFore2.SetIconPositionY(64.000000)
kElectronFore2.SetIconAboveShip(1)
kElectronFore2.SetFireSound("AndisiteElectron")
kElectronFore2.SetMaxCharge(1.25)
kElectronFore2.SetMaxDamage(85000.0)
kElectronFore2.SetMaxDamageDistance(550.0)
kElectronFore2.SetMinFiringCharge(1.0)
kElectronFore2.SetNormalDischargeRate(1.25)
kElectronFore2.SetRechargeRate(1.5)
kElectronFore2.SetIndicatorIconNum(510)
kElectronFore2.SetIndicatorIconPositionX(58.0)
kElectronFore2.SetIndicatorIconPositionY(31.0)
kElectronFore2Forward = App.TGPoint3()
kElectronFore2Forward.SetXYZ(0.0, 1.0, 0.0)
kElectronFore2Up = App.TGPoint3()
kElectronFore2Up.SetXYZ(0.0, 0.0, 1.0)
kElectronFore2.SetOrientation(kElectronFore2Forward, kElectronFore2Up)
kElectronFore2.SetWidth(0.001)
kElectronFore2.SetLength(0.001)
kElectronFore2.SetArcWidthAngles(-0.959931, 0.488692)
kElectronFore2.SetArcHeightAngles(-0.610865, 0.610865)
kElectronFore2.SetPhaserTextureStart(0)
kElectronFore2.SetPhaserTextureEnd(0)
kElectronFore2.SetPhaserWidth(0.3)
kColor = App.TGColorA()
kColor.SetRGBA(1.0, 1.0, 1.0, 1.0)
kElectronFore2.SetOuterShellColor(kColor)
kColor.SetRGBA(1.0, 1.0, 1.0, 1.0)
kElectronFore2.SetInnerShellColor(kColor)
kColor.SetRGBA(1.0, 1.0, 1.0, 1.0)
kElectronFore2.SetOuterCoreColor(kColor)
kColor.SetRGBA(1.0, 1.0, 1.0, 1.0)
kElectronFore2.SetInnerCoreColor(kColor)
kElectronFore2.SetNumSides(6)
kElectronFore2.SetMainRadius(0.05)
kElectronFore2.SetTaperRadius(0.05)
kElectronFore2.SetCoreScale(0.5)
kElectronFore2.SetTaperRatio(0.25)
kElectronFore2.SetTaperMinLength(5.0)
kElectronFore2.SetTaperMaxLength(30.0)
kElectronFore2.SetLengthTextureTilePerUnit(0.5)
kElectronFore2.SetPerimeterTile(1.0)
kElectronFore2.SetTextureSpeed(2.5)
kElectronFore2.SetTextureName("data/JLSKrenim.tga")
App.g_kModelPropertyManager.RegisterLocalTemplate(kElectronFore2)
#################################################
kElectronPort = App.PhaserProperty_Create("Electron Port")

kElectronPort.SetMaxCondition(95000.0)
kElectronPort.SetCritical(0)
kElectronPort.SetTargetable(1)
kElectronPort.SetPrimary(1)
kElectronPort.SetPosition(-0.35, 0.65, 0.0075)
kElectronPort.SetPosition2D(65.0, 5.0)
kElectronPort.SetRepairComplexity(4.0)
kElectronPort.SetDisabledPercentage(0.125)
kElectronPort.SetRadius(0.25)
kElectronPort.SetDumbfire(0)
kElectronPort.SetWeaponID(1)
kElectronPort.SetGroups(0)
kElectronPort.SetDamageRadiusFactor(0.4)
kElectronPort.SetIconNum(361)
kElectronPort.SetIconPositionX(52.000000)
kElectronPort.SetIconPositionY(37.000000)
kElectronPort.SetIconAboveShip(1)
kElectronPort.SetFireSound("AndisiteElectron")
kElectronPort.SetMaxCharge(1.25)
kElectronPort.SetMaxDamage(85000.0)
kElectronPort.SetMaxDamageDistance(550.0)
kElectronPort.SetMinFiringCharge(1.0)
kElectronPort.SetNormalDischargeRate(1.25)
kElectronPort.SetRechargeRate(1.5)
kElectronPort.SetIndicatorIconNum(508)
kElectronPort.SetIndicatorIconPositionX(50.000000)
kElectronPort.SetIndicatorIconPositionY(37.000000)
kElectronPortForward = App.TGPoint3()
kElectronPortForward.SetXYZ(-1.0, 0.0, 0.0)
kElectronPortUp = App.TGPoint3()
kElectronPortUp.SetXYZ(0.0, 0.0, 1.0)
kElectronPort.SetOrientation(kElectronPortForward, kElectronPortUp)
kElectronPort.SetWidth(0.001)
kElectronPort.SetLength(0.001)
kElectronPort.SetArcWidthAngles(-1.39626, 0.785398)
kElectronPort.SetArcHeightAngles(-0.785398, 0.610865)
kElectronPort.SetPhaserTextureStart(0)
kElectronPort.SetPhaserTextureEnd(0)
kElectronPort.SetPhaserWidth(0.3)
kColor = App.TGColorA()
kColor.SetRGBA(1.0, 1.0, 1.0, 1.0)
kElectronPort.SetOuterShellColor(kColor)
kColor.SetRGBA(1.0, 1.0, 1.0, 1.0)
kElectronPort.SetInnerShellColor(kColor)
kColor.SetRGBA(1.0, 1.0, 1.0, 1.0)
kElectronPort.SetOuterCoreColor(kColor)
kColor.SetRGBA(1.0, 1.0, 1.0, 1.0)
kElectronPort.SetInnerCoreColor(kColor)
kElectronPort.SetNumSides(6)
kElectronPort.SetMainRadius(0.05)
kElectronPort.SetTaperRadius(0.05)
kElectronPort.SetCoreScale(0.5)
kElectronPort.SetTaperRatio(0.25)
kElectronPort.SetTaperMinLength(5.0)
kElectronPort.SetTaperMaxLength(30.0)
kElectronPort.SetLengthTextureTilePerUnit(0.5)
kElectronPort.SetPerimeterTile(1.0)
kElectronPort.SetTextureSpeed(2.5)
kElectronPort.SetTextureName("data/JLSKrenim.tga")
App.g_kModelPropertyManager.RegisterLocalTemplate(kElectronPort)
#################################################
kElectronStar = App.PhaserProperty_Create("Electron Star")

kElectronStar.SetMaxCondition(95000.0)
kElectronStar.SetCritical(0)
kElectronStar.SetTargetable(1)
kElectronStar.SetPrimary(1)
kElectronStar.SetPosition(0.35, 0.65, 0.0075)
kElectronStar.SetPosition2D(65.0, 5.0)
kElectronStar.SetRepairComplexity(4.0)
kElectronStar.SetDisabledPercentage(0.125)
kElectronStar.SetRadius(0.25)
kElectronStar.SetDumbfire(0)
kElectronStar.SetWeaponID(1)
kElectronStar.SetGroups(0)
kElectronStar.SetDamageRadiusFactor(0.4)
kElectronStar.SetIconNum(362)
kElectronStar.SetIconPositionX(89.000000)
kElectronStar.SetIconPositionY(37.000000)
kElectronStar.SetIconAboveShip(1)
kElectronStar.SetFireSound("AndisiteElectron")
kElectronStar.SetMaxCharge(1.25)
kElectronStar.SetMaxDamage(85000.0)
kElectronStar.SetMaxDamageDistance(550.0)
kElectronStar.SetMinFiringCharge(1.0)
kElectronStar.SetNormalDischargeRate(1.25)
kElectronStar.SetRechargeRate(1.5)
kElectronStar.SetIndicatorIconNum(509)
kElectronStar.SetIndicatorIconPositionX(88.000000)
kElectronStar.SetIndicatorIconPositionY(37.000000)
kElectronStarForward = App.TGPoint3()
kElectronStarForward.SetXYZ(1.0, 0.0, 0.0)
kElectronStarUp = App.TGPoint3()
kElectronStarUp.SetXYZ(0.0, 0.0, 1.0)
kElectronStar.SetOrientation(kElectronStarForward, kElectronStarUp)
kElectronStar.SetWidth(0.001)
kElectronStar.SetLength(0.001)
kElectronStar.SetArcWidthAngles(-0.785398, 1.39626)
kElectronStar.SetArcHeightAngles(-0.785398, 0.610865)
kElectronStar.SetPhaserTextureStart(0)
kElectronStar.SetPhaserTextureEnd(0)
kElectronStar.SetPhaserWidth(0.3)
kColor = App.TGColorA()
kColor.SetRGBA(1.0, 1.0, 1.0, 1.0)
kElectronStar.SetOuterShellColor(kColor)
kColor.SetRGBA(1.0, 1.0, 1.0, 1.0)
kElectronStar.SetInnerShellColor(kColor)
kColor.SetRGBA(1.0, 1.0, 1.0, 1.0)
kElectronStar.SetOuterCoreColor(kColor)
kColor.SetRGBA(1.0, 1.0, 1.0, 1.0)
kElectronStar.SetInnerCoreColor(kColor)
kElectronStar.SetNumSides(6)
kElectronStar.SetMainRadius(0.05)
kElectronStar.SetTaperRadius(0.05)
kElectronStar.SetCoreScale(0.5)
kElectronStar.SetTaperRatio(0.25)
kElectronStar.SetTaperMinLength(5.0)
kElectronStar.SetTaperMaxLength(30.0)
kElectronStar.SetLengthTextureTilePerUnit(0.5)
kElectronStar.SetPerimeterTile(1.0)
kElectronStar.SetTextureSpeed(2.5)
kElectronStar.SetTextureName("data/JLSKrenim.tga")
App.g_kModelPropertyManager.RegisterLocalTemplate(kElectronStar)
#################################################
kEngineering = App.RepairSubsystemProperty_Create("Engineering")

kEngineering.SetMaxCondition(175000.0)
kEngineering.SetCritical(0)
kEngineering.SetTargetable(1)
kEngineering.SetPrimary(1)
kEngineering.SetPosition(0.0, -0.75, 0.05)
kEngineering.SetPosition2D(44.0, 70.0)
kEngineering.SetRepairComplexity(10.0)
kEngineering.SetDisabledPercentage(0.1)
kEngineering.SetRadius(0.05)
kEngineering.SetNormalPowerPerSecond(0.0)
kEngineering.SetMaxRepairPoints(1500.0)
kEngineering.SetNumRepairTeams(10)
App.g_kModelPropertyManager.RegisterLocalTemplate(kEngineering)
#################################################
kFirstPersonCamera = App.PositionOrientationProperty_Create("FirstPersonCamera")

kFirstPersonCameraForward = App.TGPoint3()
kFirstPersonCameraForward.SetXYZ(0.0, 1.0, 0.0)
kFirstPersonCameraUp = App.TGPoint3()
kFirstPersonCameraUp.SetXYZ(0.0, 0.0, 1.0)
kFirstPersonCameraRight = App.TGPoint3()
kFirstPersonCameraRight.SetXYZ(1.0, 0.0, 0.0)
kFirstPersonCamera.SetOrientation(kFirstPersonCameraForward, kFirstPersonCameraUp, kFirstPersonCameraRight)
kFirstPersonCameraPosition = App.TGPoint3()
kFirstPersonCameraPosition.SetXYZ(0.0, -0.19, 0.24)
kFirstPersonCamera.SetPosition(kFirstPersonCameraPosition)
App.g_kModelPropertyManager.RegisterLocalTemplate(kFirstPersonCamera)
#################################################
kForwardTractor = App.TractorBeamProperty_Create("Forward Tractor")

kForwardTractor.SetMaxCondition(95000.0)
kForwardTractor.SetCritical(0)
kForwardTractor.SetTargetable(1)
kForwardTractor.SetPrimary(1)
kForwardTractor.SetPosition(0.0, 1.415, -0.03)
kForwardTractor.SetPosition2D(65.0, 0.0)
kForwardTractor.SetRepairComplexity(5.0)
kForwardTractor.SetDisabledPercentage(0.25)
kForwardTractor.SetRadius(0.2)
kForwardTractor.SetDumbfire(0)
kForwardTractor.SetWeaponID(7)
kForwardTractor.SetGroups(0)
kForwardTractor.SetDamageRadiusFactor(0.3)
kForwardTractor.SetIconNum(0)
kForwardTractor.SetIconPositionX(0.0)
kForwardTractor.SetIconPositionY(0.0)
kForwardTractor.SetIconAboveShip(1)
kForwardTractor.SetFireSound("Klingon Tractor")
kForwardTractor.SetMaxCharge(5.0)
kForwardTractor.SetMaxDamage(500.0)
kForwardTractor.SetMaxDamageDistance(120.0)
kForwardTractor.SetMinFiringCharge(3.0)
kForwardTractor.SetNormalDischargeRate(1.0)
kForwardTractor.SetRechargeRate(0.3)
kForwardTractor.SetIndicatorIconNum(0)
kForwardTractor.SetIndicatorIconPositionX(0.0)
kForwardTractor.SetIndicatorIconPositionY(0.0)
kForwardTractorForward = App.TGPoint3()
kForwardTractorForward.SetXYZ(0.0, 1.0, 0.0)
kForwardTractorUp = App.TGPoint3()
kForwardTractorUp.SetXYZ(0.0, 0.0, -1.0)
kForwardTractor.SetOrientation(kForwardTractorForward, kForwardTractorUp)
kForwardTractor.SetArcWidthAngles(-0.523599, 0.523599)
kForwardTractor.SetArcHeightAngles(-0.785398, 0.785398)
kForwardTractor.SetTractorBeamWidth(0.3)
kForwardTractor.SetTextureStart(0)
kForwardTractor.SetTextureEnd(0)
kColor = App.TGColorA()
kColor.SetRGBA(0.4, 0.4, 1.0, 1.0)
kForwardTractor.SetOuterShellColor(kColor)
kColor.SetRGBA(0.4, 0.4, 1.0, 1.0)
kForwardTractor.SetInnerShellColor(kColor)
kColor.SetRGBA(0.4, 0.4, 1.0, 1.0)
kForwardTractor.SetOuterCoreColor(kColor)
kColor.SetRGBA(0.4, 0.4, 1.0, 1.0)
kForwardTractor.SetInnerCoreColor(kColor)
kForwardTractor.SetNumSides(12)
kForwardTractor.SetMainRadius(0.075)
kForwardTractor.SetTaperRadius(0.0)
kForwardTractor.SetCoreScale(0.45)
kForwardTractor.SetTaperRatio(0.2)
kForwardTractor.SetTaperMinLength(1.0)
kForwardTractor.SetTaperMaxLength(5.0)
kForwardTractor.SetLengthTextureTilePerUnit(0.25)
kForwardTractor.SetPerimeterTile(1.0)
kForwardTractor.SetTextureSpeed(0.2)
kForwardTractor.SetTextureName("data/Textures/Tactical/TractorBeam.tga")
App.g_kModelPropertyManager.RegisterLocalTemplate(kForwardTractor)
#################################################
kFwdTorpedo1 = App.TorpedoTubeProperty_Create("Fwd Torpedo 1")

kFwdTorpedo1.SetMaxCondition(125000.0)
kFwdTorpedo1.SetCritical(0)
kFwdTorpedo1.SetTargetable(1)
kFwdTorpedo1.SetPrimary(1)
kFwdTorpedo1.SetPosition(-0.075, 1.3775, -0.05)
kFwdTorpedo1.SetPosition2D(50.0, 1.0)
kFwdTorpedo1.SetRepairComplexity(3.0)
kFwdTorpedo1.SetDisabledPercentage(0.25)
kFwdTorpedo1.SetRadius(0.01)
kFwdTorpedo1.SetDumbfire(1)
kFwdTorpedo1.SetWeaponID(0)
kFwdTorpedo1.SetGroups(17)
kFwdTorpedo1.SetDamageRadiusFactor(0.2)
kFwdTorpedo1.SetIconNum(370)
kFwdTorpedo1.SetIconPositionX(69.000000)
kFwdTorpedo1.SetIconPositionY(34.000000)
kFwdTorpedo1.SetIconAboveShip(1)
kFwdTorpedo1.SetImmediateDelay(0.5)
kFwdTorpedo1.SetReloadDelay(30.0)
kFwdTorpedo1.SetMaxReady(5)
kFwdTorpedo1Direction = App.TGPoint3()
kFwdTorpedo1Direction.SetXYZ(0.0, 1.0, 0.0)
kFwdTorpedo1.SetDirection(kFwdTorpedo1Direction)
kFwdTorpedo1Right = App.TGPoint3()
kFwdTorpedo1Right.SetXYZ(-1.0, 0.0, 0.0)
kFwdTorpedo1.SetRight(kFwdTorpedo1Right)
App.g_kModelPropertyManager.RegisterLocalTemplate(kFwdTorpedo1)
#################################################
kFwdTorpedo2 = App.TorpedoTubeProperty_Create("Fwd Torpedo 2")

kFwdTorpedo2.SetMaxCondition(125000.0)
kFwdTorpedo2.SetCritical(0)
kFwdTorpedo2.SetTargetable(1)
kFwdTorpedo2.SetPrimary(1)
kFwdTorpedo2.SetPosition(0.075, 1.3775, -0.05)
kFwdTorpedo2.SetPosition2D(60.0, 1.0)
kFwdTorpedo2.SetRepairComplexity(3.0)
kFwdTorpedo2.SetDisabledPercentage(0.25)
kFwdTorpedo2.SetRadius(0.01)
kFwdTorpedo2.SetDumbfire(1)
kFwdTorpedo2.SetWeaponID(1)
kFwdTorpedo2.SetGroups(18)
kFwdTorpedo2.SetDamageRadiusFactor(0.2)
kFwdTorpedo2.SetIconNum(370)
kFwdTorpedo2.SetIconPositionX(82.000000)
kFwdTorpedo2.SetIconPositionY(34.000000)
kFwdTorpedo2.SetIconAboveShip(1)
kFwdTorpedo2.SetImmediateDelay(0.5)
kFwdTorpedo2.SetReloadDelay(30.0)
kFwdTorpedo2.SetMaxReady(5)
kFwdTorpedo2Direction = App.TGPoint3()
kFwdTorpedo2Direction.SetXYZ(0.0, 1.0, 0.0)
kFwdTorpedo2.SetDirection(kFwdTorpedo2Direction)
kFwdTorpedo2Right = App.TGPoint3()
kFwdTorpedo2Right.SetXYZ(1.0, 0.0, 0.0)
kFwdTorpedo2.SetRight(kFwdTorpedo2Right)
App.g_kModelPropertyManager.RegisterLocalTemplate(kFwdTorpedo2)
#################################################
kHull = App.HullProperty_Create("Hull")

kHull.SetMaxCondition(365000.0)
kHull.SetCritical(1)
kHull.SetTargetable(1)
kHull.SetPrimary(1)
kHull.SetPosition(0.0, 0.0, 0.0)
kHull.SetPosition2D(65.0, 23.0)
kHull.SetRepairComplexity(3.0)
kHull.SetDisabledPercentage(0.0)
kHull.SetRadius(0.35)
App.g_kModelPropertyManager.RegisterLocalTemplate(kHull)
#################################################
kNaniteInjector = App.RepairSubsystemProperty_Create("Nanite Injector")

kNaniteInjector.SetMaxCondition(175000.0)
kNaniteInjector.SetCritical(0)
kNaniteInjector.SetTargetable(1)
kNaniteInjector.SetPrimary(1)
kNaniteInjector.SetPosition(0.0, -0.1, -0.05)
kNaniteInjector.SetPosition2D(64.0, 80.0)
kNaniteInjector.SetRepairComplexity(4.0)
kNaniteInjector.SetDisabledPercentage(0.1)
kNaniteInjector.SetRadius(0.125)
kNaniteInjector.SetNormalPowerPerSecond(1.0)
kNaniteInjector.SetMaxRepairPoints(1500.0)
kNaniteInjector.SetNumRepairTeams(10)
App.g_kModelPropertyManager.RegisterLocalTemplate(kNaniteInjector)
#################################################
kNeutralmatterCloak = App.CloakingSubsystemProperty_Create("Neutralmatter Cloak")

kNeutralmatterCloak.SetMaxCondition(250000.0)
kNeutralmatterCloak.SetCritical(0)
kNeutralmatterCloak.SetTargetable(1)
kNeutralmatterCloak.SetPrimary(1)
kNeutralmatterCloak.SetPosition(0.0, 0.5, 0.0)
kNeutralmatterCloak.SetPosition2D(64.0, 45.0)
kNeutralmatterCloak.SetRepairComplexity(2.0)
kNeutralmatterCloak.SetDisabledPercentage(0.05)
kNeutralmatterCloak.SetRadius(0.05)
kNeutralmatterCloak.SetNormalPowerPerSecond(4000.0)
kNeutralmatterCloak.SetCloakStrength(9500.0)
App.g_kModelPropertyManager.RegisterLocalTemplate(kNeutralmatterCloak)
#################################################
kPlasmaDrive = App.ImpulseEngineProperty_Create("Plasma Drive")

kPlasmaDrive.SetMaxCondition(300000.0)
kPlasmaDrive.SetCritical(0)
kPlasmaDrive.SetTargetable(1)
kPlasmaDrive.SetPrimary(1)
kPlasmaDrive.SetPosition(0.0, -1.0, 0.0)
kPlasmaDrive.SetPosition2D(64.0, 104.0)
kPlasmaDrive.SetRepairComplexity(4.0)
kPlasmaDrive.SetDisabledPercentage(0.25)
kPlasmaDrive.SetRadius(0.065)
kPlasmaDrive.SetNormalPowerPerSecond(50.0)
kPlasmaDrive.SetMaxAccel(15.5)
kPlasmaDrive.SetMaxAngularAccel(1.25)
kPlasmaDrive.SetMaxAngularVelocity(1.5)
kPlasmaDrive.SetMaxSpeed(20.0)
kPlasmaDrive.SetEngineSound("Andisite Engines")
App.g_kModelPropertyManager.RegisterLocalTemplate(kPlasmaDrive)
#################################################
kPlasmaPulse1 = App.PulseWeaponProperty_Create("Plasma Pulse 1")

kPlasmaPulse1.SetMaxCondition(150000.0)
kPlasmaPulse1.SetCritical(0)
kPlasmaPulse1.SetTargetable(1)
kPlasmaPulse1.SetPrimary(1)
kPlasmaPulse1.SetPosition(-0.7, -0.1, -0.1075)
kPlasmaPulse1.SetPosition2D(0.0, 0.0)
kPlasmaPulse1.SetRepairComplexity(1.0)
kPlasmaPulse1.SetDisabledPercentage(0.25)
kPlasmaPulse1.SetRadius(0.25)
kPlasmaPulse1.SetDumbfire(1)
kPlasmaPulse1.SetWeaponID(0)
kPlasmaPulse1.SetGroups(0)
kPlasmaPulse1.SetDamageRadiusFactor(0.3)
kPlasmaPulse1.SetIconNum(365)
kPlasmaPulse1.SetIconPositionX(96.000000)
kPlasmaPulse1.SetIconPositionY(78.000000)
kPlasmaPulse1.SetIconAboveShip(1)
kPlasmaPulse1.SetFireSound("AndisitePlasmaPulse")
kPlasmaPulse1.SetMaxCharge(2.0)
kPlasmaPulse1.SetMaxDamage(2500.0)
kPlasmaPulse1.SetMaxDamageDistance(100.0)
kPlasmaPulse1.SetMinFiringCharge(1.0)
kPlasmaPulse1.SetNormalDischargeRate(1.0)
kPlasmaPulse1.SetRechargeRate(2.5)
kPlasmaPulse1.SetIndicatorIconNum(0)
kPlasmaPulse1.SetIndicatorIconPositionX(98.000000)
kPlasmaPulse1.SetIndicatorIconPositionY(82.000000)
kPlasmaPulse1Forward = App.TGPoint3()
kPlasmaPulse1Forward.SetXYZ(0.0, 1.0, 0.0)
kPlasmaPulse1Up = App.TGPoint3()
kPlasmaPulse1Up.SetXYZ(0.0, 0.0, 1.0)
kPlasmaPulse1.SetOrientation(kPlasmaPulse1Forward, kPlasmaPulse1Up)
kPlasmaPulse1.SetArcWidthAngles(-0.959931, 0.488692)
kPlasmaPulse1.SetArcHeightAngles(-0.610865, 0.610865)
kPlasmaPulse1.SetCooldownTime(0.5)
kPlasmaPulse1.SetModuleName("Tactical.Projectiles.AndisitePlasmaPulse")
App.g_kModelPropertyManager.RegisterLocalTemplate(kPlasmaPulse1)
#################################################
kPlasmaPulse2 = App.PulseWeaponProperty_Create("Plasma Pulse 2")

kPlasmaPulse2.SetMaxCondition(150000.0)
kPlasmaPulse2.SetCritical(0)
kPlasmaPulse2.SetTargetable(1)
kPlasmaPulse2.SetPrimary(1)
kPlasmaPulse2.SetPosition(0.7, -0.1, -0.1075)
kPlasmaPulse2.SetPosition2D(0.0, 0.0)
kPlasmaPulse2.SetRepairComplexity(1.0)
kPlasmaPulse2.SetDisabledPercentage(0.25)
kPlasmaPulse2.SetRadius(0.25)
kPlasmaPulse2.SetDumbfire(1)
kPlasmaPulse2.SetWeaponID(0)
kPlasmaPulse2.SetGroups(0)
kPlasmaPulse2.SetDamageRadiusFactor(0.3)
kPlasmaPulse2.SetIconNum(365)
kPlasmaPulse2.SetIconPositionX(57.000000)
kPlasmaPulse2.SetIconPositionY(78.000000)
kPlasmaPulse2.SetIconAboveShip(1)
kPlasmaPulse2.SetFireSound("AndisitePlasmaPulse")
kPlasmaPulse2.SetMaxCharge(2.0)
kPlasmaPulse2.SetMaxDamage(2500.0)
kPlasmaPulse2.SetMaxDamageDistance(100.0)
kPlasmaPulse2.SetMinFiringCharge(1.0)
kPlasmaPulse2.SetNormalDischargeRate(1.0)
kPlasmaPulse2.SetRechargeRate(2.5)
kPlasmaPulse2.SetIndicatorIconNum(0)
kPlasmaPulse2.SetIndicatorIconPositionX(59.000000)
kPlasmaPulse2.SetIndicatorIconPositionY(82.000000)
kPlasmaPulse2Forward = App.TGPoint3()
kPlasmaPulse2Forward.SetXYZ(0.0, 1.0, 0.0)
kPlasmaPulse2Up = App.TGPoint3()
kPlasmaPulse2Up.SetXYZ(0.0, 0.0, 1.0)
kPlasmaPulse2.SetOrientation(kPlasmaPulse2Forward, kPlasmaPulse2Up)
kPlasmaPulse2.SetArcWidthAngles(-0.488692, 0.959931)
kPlasmaPulse2.SetArcHeightAngles(-0.610865, 0.610865)
kPlasmaPulse2.SetCooldownTime(0.5)
kPlasmaPulse2.SetModuleName("Tactical.Projectiles.AndisitePlasmaPulse")
App.g_kModelPropertyManager.RegisterLocalTemplate(kPlasmaPulse2)
#################################################
kPlasmaPulse3 = App.PulseWeaponProperty_Create("Plasma Pulse 3")

kPlasmaPulse3.SetMaxCondition(150000.0)
kPlasmaPulse3.SetCritical(0)
kPlasmaPulse3.SetTargetable(1)
kPlasmaPulse3.SetPrimary(1)
kPlasmaPulse3.SetPosition(0.0, -1.35, 0.08)
kPlasmaPulse3.SetPosition2D(0.0, 0.0)
kPlasmaPulse3.SetRepairComplexity(1.0)
kPlasmaPulse3.SetDisabledPercentage(0.25)
kPlasmaPulse3.SetRadius(0.25)
kPlasmaPulse3.SetDumbfire(1)
kPlasmaPulse3.SetWeaponID(0)
kPlasmaPulse3.SetGroups(0)
kPlasmaPulse3.SetDamageRadiusFactor(0.3)
kPlasmaPulse3.SetIconNum(366)
kPlasmaPulse3.SetIconPositionX(77.000000)
kPlasmaPulse3.SetIconPositionY(123.000000)
kPlasmaPulse3.SetIconAboveShip(1)
kPlasmaPulse3.SetFireSound("AndisitePlasmaPulse")
kPlasmaPulse3.SetMaxCharge(2.0)
kPlasmaPulse3.SetMaxDamage(2500.0)
kPlasmaPulse3.SetMaxDamageDistance(100.0)
kPlasmaPulse3.SetMinFiringCharge(1.0)
kPlasmaPulse3.SetNormalDischargeRate(1.0)
kPlasmaPulse3.SetRechargeRate(2.5)
kPlasmaPulse3.SetIndicatorIconNum(0)
kPlasmaPulse3.SetIndicatorIconPositionX(79.000000)
kPlasmaPulse3.SetIndicatorIconPositionY(127.000000)
kPlasmaPulse3Forward = App.TGPoint3()
kPlasmaPulse3Forward.SetXYZ(0.0, -1.0, 0.0)
kPlasmaPulse3Up = App.TGPoint3()
kPlasmaPulse3Up.SetXYZ(0.0, 0.0, 1.0)
kPlasmaPulse3.SetOrientation(kPlasmaPulse3Forward, kPlasmaPulse3Up)
kPlasmaPulse3.SetArcWidthAngles(-0.959931, 0.959931)
kPlasmaPulse3.SetArcHeightAngles(-0.959931, 0.959931)
kPlasmaPulse3.SetCooldownTime(0.5)
kPlasmaPulse3.SetModuleName("Tactical.Projectiles.AndisitePlasmaPulse")
App.g_kModelPropertyManager.RegisterLocalTemplate(kPlasmaPulse3)
#################################################
kPlasmaPulseGenerator = App.WeaponSystemProperty_Create("Plasma Pulse Generator")

kPlasmaPulseGenerator.SetMaxCondition(275000.0)
kPlasmaPulseGenerator.SetCritical(0)
kPlasmaPulseGenerator.SetTargetable(1)
kPlasmaPulseGenerator.SetPrimary(1)
kPlasmaPulseGenerator.SetPosition(0.0, -0.75, 0.15)
kPlasmaPulseGenerator.SetPosition2D(0.0, 0.0)
kPlasmaPulseGenerator.SetRepairComplexity(5.0)
kPlasmaPulseGenerator.SetDisabledPercentage(0.25)
kPlasmaPulseGenerator.SetRadius(0.025)
kPlasmaPulseGenerator.SetNormalPowerPerSecond(50.0)
kPlasmaPulseGenerator.SetWeaponSystemType(kPlasmaPulseGenerator.WST_PULSE)
kPlasmaPulseGenerator.SetSingleFire(1)
kPlasmaPulseGenerator.SetAimedWeapon(1)
kFiringChainString = App.TGString()
kFiringChainString.SetString("")
kPlasmaPulseGenerator.SetFiringChainString(kFiringChainString)
App.g_kModelPropertyManager.RegisterLocalTemplate(kPlasmaPulseGenerator)
#################################################
kPlasmaShieldGenerator = App.ShieldProperty_Create("Plasma Shield Generator")

kPlasmaShieldGenerator.SetMaxCondition(325000.0)
kPlasmaShieldGenerator.SetCritical(0)
kPlasmaShieldGenerator.SetTargetable(1)
kPlasmaShieldGenerator.SetPrimary(1)
kPlasmaShieldGenerator.SetPosition(0.0, 0.26, 0.075)
kPlasmaShieldGenerator.SetPosition2D(65.0, 39.0)
kPlasmaShieldGenerator.SetRepairComplexity(2.0)
kPlasmaShieldGenerator.SetDisabledPercentage(0.25)
kPlasmaShieldGenerator.SetRadius(0.05)
kPlasmaShieldGenerator.SetNormalPowerPerSecond(180.0)
kPlasmaShieldGeneratorShieldGlowColor = App.TGColorA()
kPlasmaShieldGeneratorShieldGlowColor.SetRGBA(0.501961, 0.0, 1.0, 0.466667)
kPlasmaShieldGenerator.SetShieldGlowColor(kPlasmaShieldGeneratorShieldGlowColor)
kPlasmaShieldGenerator.SetShieldGlowDecay(5.0)
kPlasmaShieldGenerator.SetMaxShields(kPlasmaShieldGenerator.FRONT_SHIELDS, 215000.0)
kPlasmaShieldGenerator.SetMaxShields(kPlasmaShieldGenerator.REAR_SHIELDS, 215000.0)
kPlasmaShieldGenerator.SetMaxShields(kPlasmaShieldGenerator.TOP_SHIELDS, 215000.0)
kPlasmaShieldGenerator.SetMaxShields(kPlasmaShieldGenerator.BOTTOM_SHIELDS, 215000.0)
kPlasmaShieldGenerator.SetMaxShields(kPlasmaShieldGenerator.LEFT_SHIELDS, 215000.0)
kPlasmaShieldGenerator.SetMaxShields(kPlasmaShieldGenerator.RIGHT_SHIELDS, 215000.0)
kPlasmaShieldGenerator.SetShieldChargePerSecond(kPlasmaShieldGenerator.FRONT_SHIELDS, 500.0)
kPlasmaShieldGenerator.SetShieldChargePerSecond(kPlasmaShieldGenerator.REAR_SHIELDS, 500.0)
kPlasmaShieldGenerator.SetShieldChargePerSecond(kPlasmaShieldGenerator.TOP_SHIELDS, 500.0)
kPlasmaShieldGenerator.SetShieldChargePerSecond(kPlasmaShieldGenerator.BOTTOM_SHIELDS, 500.0)
kPlasmaShieldGenerator.SetShieldChargePerSecond(kPlasmaShieldGenerator.LEFT_SHIELDS, 500.0)
kPlasmaShieldGenerator.SetShieldChargePerSecond(kPlasmaShieldGenerator.RIGHT_SHIELDS, 500.0)
App.g_kModelPropertyManager.RegisterLocalTemplate(kPlasmaShieldGenerator)
#################################################
kPlasmaticArmor = App.HullProperty_Create("Plasmatic Armor")

kPlasmaticArmor.SetMaxCondition(485000.0)
kPlasmaticArmor.SetCritical(0)
kPlasmaticArmor.SetTargetable(1)
kPlasmaticArmor.SetPrimary(0)
kPlasmaticArmor.SetPosition(0.0, 0.0, -0.1)
kPlasmaticArmor.SetPosition2D(0.0, 0.0)
kPlasmaticArmor.SetRepairComplexity(1.0)
kPlasmaticArmor.SetDisabledPercentage(0.05)
kPlasmaticArmor.SetRadius(10.0)
App.g_kModelPropertyManager.RegisterLocalTemplate(kPlasmaticArmor)
#################################################
kPortImpulse = App.EngineProperty_Create("Port Plasma Drive")

kPortImpulse.SetMaxCondition(225000.0)
kPortImpulse.SetCritical(0)
kPortImpulse.SetTargetable(1)
kPortImpulse.SetPrimary(1)
kPortImpulse.SetPosition(-0.09, -1.225, -0.025)
kPortImpulse.SetPosition2D(35.0, 67.0)
kPortImpulse.SetRepairComplexity(4.0)
kPortImpulse.SetDisabledPercentage(0.25)
kPortImpulse.SetRadius(0.025)
kPortImpulse.SetEngineType(kPortImpulse.EP_IMPULSE)
App.g_kModelPropertyManager.RegisterLocalTemplate(kPortImpulse)
#################################################
kSensorArray = App.SensorProperty_Create("Sensor Array")

kSensorArray.SetMaxCondition(315000.0)
kSensorArray.SetCritical(0)
kSensorArray.SetTargetable(1)
kSensorArray.SetPrimary(1)
kSensorArray.SetPosition(0.0, 1.4, -0.035)
kSensorArray.SetPosition2D(65.0, 8.0)
kSensorArray.SetRepairComplexity(1.0)
kSensorArray.SetDisabledPercentage(0.25)
kSensorArray.SetRadius(0.05)
kSensorArray.SetNormalPowerPerSecond(50.0)
kSensorArray.SetBaseSensorRange(350000.0)
kSensorArray.SetMaxProbes(10)
App.g_kModelPropertyManager.RegisterLocalTemplate(kSensorArray)
#################################################
kStarImpulse = App.EngineProperty_Create("Star Plasma Drive")

kStarImpulse.SetMaxCondition(225000.0)
kStarImpulse.SetCritical(0)
kStarImpulse.SetTargetable(1)
kStarImpulse.SetPrimary(1)
kStarImpulse.SetPosition(0.1, -1.225, -0.025)
kStarImpulse.SetPosition2D(93.0, 67.0)
kStarImpulse.SetRepairComplexity(4.0)
kStarImpulse.SetDisabledPercentage(0.25)
kStarImpulse.SetRadius(0.025)
kStarImpulse.SetEngineType(kStarImpulse.EP_IMPULSE)
App.g_kModelPropertyManager.RegisterLocalTemplate(kStarImpulse)
#################################################
kTorpedoes = App.TorpedoSystemProperty_Create("Torpedoes")

kTorpedoes.SetMaxCondition(345000.0)
kTorpedoes.SetCritical(0)
kTorpedoes.SetTargetable(1)
kTorpedoes.SetPrimary(1)
kTorpedoes.SetPosition(0.0, 0.45, 0.05)
kTorpedoes.SetPosition2D(64.0, 10.0)
kTorpedoes.SetRepairComplexity(3.0)
kTorpedoes.SetDisabledPercentage(0.25)
kTorpedoes.SetRadius(0.05)
kTorpedoes.SetNormalPowerPerSecond(50.0)
kTorpedoes.SetWeaponSystemType(kTorpedoes.WST_TORPEDO)
kTorpedoes.SetSingleFire(0)
kTorpedoes.SetAimedWeapon(1)
kFiringChainString = App.TGString()
kFiringChainString.SetString("0;Single;123;Dual;5;Full")
kTorpedoes.SetFiringChainString(kFiringChainString)
kTorpedoes.SetMaxTorpedoes(0, 350)
kTorpedoes.SetTorpedoScript(0, "Tactical.Projectiles.AndisiteLightPlasma")
kTorpedoes.SetMaxTorpedoes(1, 85)
kTorpedoes.SetTorpedoScript(1, "Tactical.Projectiles.AndisiteHeavyPlasma")
kTorpedoes.SetNumAmmoTypes(2)
App.g_kModelPropertyManager.RegisterLocalTemplate(kTorpedoes)
#################################################
kTractors = App.WeaponSystemProperty_Create("Tractors")

kTractors.SetMaxCondition(200000.0)
kTractors.SetCritical(0)
kTractors.SetTargetable(1)
kTractors.SetPrimary(1)
kTractors.SetPosition(0.0, 0.5, -0.1)
kTractors.SetPosition2D(39.0, 72.0)
kTractors.SetRepairComplexity(7.0)
kTractors.SetDisabledPercentage(0.5)
kTractors.SetRadius(0.1)
kTractors.SetNormalPowerPerSecond(700.0)
kTractors.SetWeaponSystemType(kTractors.WST_TRACTOR)
kTractors.SetSingleFire(1)
kTractors.SetAimedWeapon(0)
kFiringChainString = App.TGString()
kFiringChainString.SetString("")
kTractors.SetFiringChainString(kFiringChainString)
App.g_kModelPropertyManager.RegisterLocalTemplate(kTractors)
#################################################
kViewscreenBack = App.PositionOrientationProperty_Create("ViewscreenBack")

kViewscreenBackForward = App.TGPoint3()
kViewscreenBackForward.SetXYZ(0.0, -1.0, 0.0)
kViewscreenBackUp = App.TGPoint3()
kViewscreenBackUp.SetXYZ(0.0, 0.0, 1.0)
kViewscreenBackRight = App.TGPoint3()
kViewscreenBackRight.SetXYZ(-1.0, 0.0, 0.0)
kViewscreenBack.SetOrientation(kViewscreenBackForward, kViewscreenBackUp, kViewscreenBackRight)
kViewscreenBackPosition = App.TGPoint3()
kViewscreenBackPosition.SetXYZ(0.0, -0.775, 0.125)
kViewscreenBack.SetPosition(kViewscreenBackPosition)
App.g_kModelPropertyManager.RegisterLocalTemplate(kViewscreenBack)
#################################################
kViewscreenDown = App.PositionOrientationProperty_Create("ViewscreenDown")

kViewscreenDownForward = App.TGPoint3()
kViewscreenDownForward.SetXYZ(0.0, 0.0, -1.0)
kViewscreenDownUp = App.TGPoint3()
kViewscreenDownUp.SetXYZ(0.0, 1.0, 0.0)
kViewscreenDownRight = App.TGPoint3()
kViewscreenDownRight.SetXYZ(1.0, 0.0, 0.0)
kViewscreenDown.SetOrientation(kViewscreenDownForward, kViewscreenDownUp, kViewscreenDownRight)
kViewscreenDownPosition = App.TGPoint3()
kViewscreenDownPosition.SetXYZ(0.0, 0.0, -0.4)
kViewscreenDown.SetPosition(kViewscreenDownPosition)
App.g_kModelPropertyManager.RegisterLocalTemplate(kViewscreenDown)
#################################################
kViewscreenForward = App.PositionOrientationProperty_Create("ViewscreenForward")

kViewscreenForwardForward = App.TGPoint3()
kViewscreenForwardForward.SetXYZ(0.0, 1.0, 0.0)
kViewscreenForwardUp = App.TGPoint3()
kViewscreenForwardUp.SetXYZ(0.0, 0.0, 1.0)
kViewscreenForwardRight = App.TGPoint3()
kViewscreenForwardRight.SetXYZ(1.0, 0.0, 0.0)
kViewscreenForward.SetOrientation(kViewscreenForwardForward, kViewscreenForwardUp, kViewscreenForwardRight)
kViewscreenForwardPosition = App.TGPoint3()
kViewscreenForwardPosition.SetXYZ(0.0, 1.45, -0.03)
kViewscreenForward.SetPosition(kViewscreenForwardPosition)
App.g_kModelPropertyManager.RegisterLocalTemplate(kViewscreenForward)
#################################################
kViewscreenLeft = App.PositionOrientationProperty_Create("ViewscreenLeft")

kViewscreenLeftForward = App.TGPoint3()
kViewscreenLeftForward.SetXYZ(-1.0, 0.0, 0.0)
kViewscreenLeftUp = App.TGPoint3()
kViewscreenLeftUp.SetXYZ(0.0, 0.0, 1.0)
kViewscreenLeftRight = App.TGPoint3()
kViewscreenLeftRight.SetXYZ(0.0, 1.0, 0.0)
kViewscreenLeft.SetOrientation(kViewscreenLeftForward, kViewscreenLeftUp, kViewscreenLeftRight)
kViewscreenLeftPosition = App.TGPoint3()
kViewscreenLeftPosition.SetXYZ(-1.7, 0.0, 0.0)
kViewscreenLeft.SetPosition(kViewscreenLeftPosition)
App.g_kModelPropertyManager.RegisterLocalTemplate(kViewscreenLeft)
#################################################
kViewscreenRight = App.PositionOrientationProperty_Create("ViewscreenRight")

kViewscreenRightForward = App.TGPoint3()
kViewscreenRightForward.SetXYZ(1.0, 0.0, 0.0)
kViewscreenRightUp = App.TGPoint3()
kViewscreenRightUp.SetXYZ(0.0, 0.0, 1.0)
kViewscreenRightRight = App.TGPoint3()
kViewscreenRightRight.SetXYZ(0.0, -1.0, 0.0)
kViewscreenRight.SetOrientation(kViewscreenRightForward, kViewscreenRightUp, kViewscreenRightRight)
kViewscreenRightPosition = App.TGPoint3()
kViewscreenRightPosition.SetXYZ(1.7, 0.0, 0.0)
kViewscreenRight.SetPosition(kViewscreenRightPosition)
App.g_kModelPropertyManager.RegisterLocalTemplate(kViewscreenRight)
#################################################
kViewscreenUp = App.PositionOrientationProperty_Create("ViewscreenUp")

kViewscreenUpForward = App.TGPoint3()
kViewscreenUpForward.SetXYZ(0.0, 0.0, 1.0)
kViewscreenUpUp = App.TGPoint3()
kViewscreenUpUp.SetXYZ(0.0, -1.0, 0.0)
kViewscreenUpRight = App.TGPoint3()
kViewscreenUpRight.SetXYZ(1.0, 0.0, 0.0)
kViewscreenUp.SetOrientation(kViewscreenUpForward, kViewscreenUpUp, kViewscreenUpRight)
kViewscreenUpPosition = App.TGPoint3()
kViewscreenUpPosition.SetXYZ(0.0, 0.0, 0.4)
kViewscreenUp.SetPosition(kViewscreenUpPosition)
App.g_kModelPropertyManager.RegisterLocalTemplate(kViewscreenUp)
#################################################
kWarpDrive = App.WarpEngineProperty_Create("Spiral Hyperfusion Drive")

kWarpDrive.SetMaxCondition(300000.0)
kWarpDrive.SetCritical(0)
kWarpDrive.SetTargetable(1)
kWarpDrive.SetPrimary(1)
kWarpDrive.SetPosition(0.0, -0.5, -0.5)
kWarpDrive.SetPosition2D(64.0, 104.0)
kWarpDrive.SetRepairComplexity(3.0)
kWarpDrive.SetDisabledPercentage(0.25)
kWarpDrive.SetRadius(0.075)
kWarpDrive.SetNormalPowerPerSecond(0.0)
App.g_kModelPropertyManager.RegisterLocalTemplate(kWarpDrive)
#################################################
kWarpEngine = App.EngineProperty_Create("Hyperfusion Drive Regulator")

kWarpEngine.SetMaxCondition(225000.0)
kWarpEngine.SetCritical(0)
kWarpEngine.SetTargetable(1)
kWarpEngine.SetPrimary(1)
kWarpEngine.SetPosition(0.0, -0.65, -0.425)
kWarpEngine.SetPosition2D(65.0, 92.0)
kWarpEngine.SetRepairComplexity(3.0)
kWarpEngine.SetDisabledPercentage(0.25)
kWarpEngine.SetRadius(0.065)
kWarpEngine.SetEngineType(kWarpEngine.EP_WARP)
App.g_kModelPropertyManager.RegisterLocalTemplate(kWarpEngine)
#################################################
ArmourGenerator = App.HullProperty_Create("Armored Hull")

ArmourGenerator.SetMaxCondition(485000.000000)
ArmourGenerator.SetCritical(0)
ArmourGenerator.SetTargetable(0)
ArmourGenerator.SetPrimary(0)
ArmourGenerator.SetPosition(0.000000, 0.000000, 0.000000)
ArmourGenerator.SetPosition2D(0.000000, 0.000000)
ArmourGenerator.SetRepairComplexity(2.000000)
ArmourGenerator.SetDisabledPercentage(0.500000)
ArmourGenerator.SetRadius(0.250000)
App.g_kModelPropertyManager.RegisterLocalTemplate(ArmourGenerator)

# Property Set
def LoadPropertySet(pObj):
	prop = App.g_kModelPropertyManager.FindByName("Hull", App.TGModelPropertyManager.LOCAL_TEMPLATES)
	if (prop != None):
		pObj.AddToSet("Scene Root", prop)
	prop = App.g_kModelPropertyManager.FindByName("Armored Hull", App.TGModelPropertyManager.LOCAL_TEMPLATES)
	if (prop != None):
		pObj.AddToSet("Scene Root", prop)
	prop = App.g_kModelPropertyManager.FindByName("Aft Torpedo 1", App.TGModelPropertyManager.LOCAL_TEMPLATES)
	if (prop != None):
		pObj.AddToSet("Scene Root", prop)
	prop = App.g_kModelPropertyManager.FindByName("Aft Torpedo 2", App.TGModelPropertyManager.LOCAL_TEMPLATES)
	if (prop != None):
		pObj.AddToSet("Scene Root", prop)
	prop = App.g_kModelPropertyManager.FindByName("Aft Tractor", App.TGModelPropertyManager.LOCAL_TEMPLATES)
	if (prop != None):
		pObj.AddToSet("Scene Root", prop)
	prop = App.g_kModelPropertyManager.FindByName("AndisiteAC", App.TGModelPropertyManager.LOCAL_TEMPLATES)
	if (prop != None):
		pObj.AddToSet("Scene Root", prop)
	prop = App.g_kModelPropertyManager.FindByName("Crystaline Core", App.TGModelPropertyManager.LOCAL_TEMPLATES)
	if (prop != None):
		pObj.AddToSet("Scene Root", prop)
	prop = App.g_kModelPropertyManager.FindByName("Electron Aft", App.TGModelPropertyManager.LOCAL_TEMPLATES)
	if (prop != None):
		pObj.AddToSet("Scene Root", prop)
	prop = App.g_kModelPropertyManager.FindByName("Electron Beam Core", App.TGModelPropertyManager.LOCAL_TEMPLATES)
	if (prop != None):
		pObj.AddToSet("Scene Root", prop)
	prop = App.g_kModelPropertyManager.FindByName("Electron Fore 1", App.TGModelPropertyManager.LOCAL_TEMPLATES)
	if (prop != None):
		pObj.AddToSet("Scene Root", prop)
	prop = App.g_kModelPropertyManager.FindByName("Electron Fore 2", App.TGModelPropertyManager.LOCAL_TEMPLATES)
	if (prop != None):
		pObj.AddToSet("Scene Root", prop)
	prop = App.g_kModelPropertyManager.FindByName("Electron Port", App.TGModelPropertyManager.LOCAL_TEMPLATES)
	if (prop != None):
		pObj.AddToSet("Scene Root", prop)
	prop = App.g_kModelPropertyManager.FindByName("Electron Star", App.TGModelPropertyManager.LOCAL_TEMPLATES)
	if (prop != None):
		pObj.AddToSet("Scene Root", prop)
	prop = App.g_kModelPropertyManager.FindByName("Engineering", App.TGModelPropertyManager.LOCAL_TEMPLATES)
	if (prop != None):
		pObj.AddToSet("Scene Root", prop)
	prop = App.g_kModelPropertyManager.FindByName("FirstPersonCamera", App.TGModelPropertyManager.LOCAL_TEMPLATES)
	if (prop != None):
		pObj.AddToSet("Scene Root", prop)
	prop = App.g_kModelPropertyManager.FindByName("Forward Tractor", App.TGModelPropertyManager.LOCAL_TEMPLATES)
	if (prop != None):
		pObj.AddToSet("Scene Root", prop)
	prop = App.g_kModelPropertyManager.FindByName("Fwd Torpedo 1", App.TGModelPropertyManager.LOCAL_TEMPLATES)
	if (prop != None):
		pObj.AddToSet("Scene Root", prop)
	prop = App.g_kModelPropertyManager.FindByName("Fwd Torpedo 2", App.TGModelPropertyManager.LOCAL_TEMPLATES)
	if (prop != None):
		pObj.AddToSet("Scene Root", prop)
	prop = App.g_kModelPropertyManager.FindByName("Nanite Injector", App.TGModelPropertyManager.LOCAL_TEMPLATES)
	if (prop != None):
		pObj.AddToSet("Scene Root", prop)
	prop = App.g_kModelPropertyManager.FindByName("Neutralmatter Cloak", App.TGModelPropertyManager.LOCAL_TEMPLATES)
	if (prop != None):
		pObj.AddToSet("Scene Root", prop)
	prop = App.g_kModelPropertyManager.FindByName("Plasma Drive", App.TGModelPropertyManager.LOCAL_TEMPLATES)
	if (prop != None):
		pObj.AddToSet("Scene Root", prop)
	prop = App.g_kModelPropertyManager.FindByName("Plasma Pulse 1", App.TGModelPropertyManager.LOCAL_TEMPLATES)
	if (prop != None):
		pObj.AddToSet("Scene Root", prop)
	prop = App.g_kModelPropertyManager.FindByName("Plasma Pulse 2", App.TGModelPropertyManager.LOCAL_TEMPLATES)
	if (prop != None):
		pObj.AddToSet("Scene Root", prop)
	prop = App.g_kModelPropertyManager.FindByName("Plasma Pulse 3", App.TGModelPropertyManager.LOCAL_TEMPLATES)
	if (prop != None):
		pObj.AddToSet("Scene Root", prop)
	prop = App.g_kModelPropertyManager.FindByName("Plasma Pulse Generator", App.TGModelPropertyManager.LOCAL_TEMPLATES)
	if (prop != None):
		pObj.AddToSet("Scene Root", prop)
	prop = App.g_kModelPropertyManager.FindByName("Plasma Shield Generator", App.TGModelPropertyManager.LOCAL_TEMPLATES)
	if (prop != None):
		pObj.AddToSet("Scene Root", prop)
	prop = App.g_kModelPropertyManager.FindByName("Port Plasma Drive", App.TGModelPropertyManager.LOCAL_TEMPLATES)
	if (prop != None):
		pObj.AddToSet("Scene Root", prop)
	prop = App.g_kModelPropertyManager.FindByName("Sensor Array", App.TGModelPropertyManager.LOCAL_TEMPLATES)
	if (prop != None):
		pObj.AddToSet("Scene Root", prop)
	prop = App.g_kModelPropertyManager.FindByName("Star Plasma Drive", App.TGModelPropertyManager.LOCAL_TEMPLATES)
	if (prop != None):
		pObj.AddToSet("Scene Root", prop)
	prop = App.g_kModelPropertyManager.FindByName("Torpedoes", App.TGModelPropertyManager.LOCAL_TEMPLATES)
	if (prop != None):
		pObj.AddToSet("Scene Root", prop)
	prop = App.g_kModelPropertyManager.FindByName("Tractors", App.TGModelPropertyManager.LOCAL_TEMPLATES)
	if (prop != None):
		pObj.AddToSet("Scene Root", prop)
	prop = App.g_kModelPropertyManager.FindByName("ViewscreenBack", App.TGModelPropertyManager.LOCAL_TEMPLATES)
	if (prop != None):
		pObj.AddToSet("Scene Root", prop)
	prop = App.g_kModelPropertyManager.FindByName("ViewscreenDown", App.TGModelPropertyManager.LOCAL_TEMPLATES)
	if (prop != None):
		pObj.AddToSet("Scene Root", prop)
	prop = App.g_kModelPropertyManager.FindByName("ViewscreenForward", App.TGModelPropertyManager.LOCAL_TEMPLATES)
	if (prop != None):
		pObj.AddToSet("Scene Root", prop)
	prop = App.g_kModelPropertyManager.FindByName("ViewscreenLeft", App.TGModelPropertyManager.LOCAL_TEMPLATES)
	if (prop != None):
		pObj.AddToSet("Scene Root", prop)
	prop = App.g_kModelPropertyManager.FindByName("ViewscreenRight", App.TGModelPropertyManager.LOCAL_TEMPLATES)
	if (prop != None):
		pObj.AddToSet("Scene Root", prop)
	prop = App.g_kModelPropertyManager.FindByName("ViewscreenUp", App.TGModelPropertyManager.LOCAL_TEMPLATES)
	if (prop != None):
		pObj.AddToSet("Scene Root", prop)
	prop = App.g_kModelPropertyManager.FindByName("Spiral Hyperfusion Drive", App.TGModelPropertyManager.LOCAL_TEMPLATES)
	if (prop != None):
		pObj.AddToSet("Scene Root", prop)
	prop = App.g_kModelPropertyManager.FindByName("Hyperfusion Drive Regulator", App.TGModelPropertyManager.LOCAL_TEMPLATES)
	if (prop != None):
		pObj.AddToSet("Scene Root", prop)
