# File: Z (Python 1.5)

import App
import GlobalPropertyTemplates
# Setting up local templates.
#################################################
FwdLauncher = App.TorpedoTubeProperty_Create('Fwd Launcher')
FwdLauncher.SetMaxCondition(2500.0)
FwdLauncher.SetCritical(0)
FwdLauncher.SetTargetable(1)
FwdLauncher.SetPrimary(1)
FwdLauncher.SetPosition(0.0, 0.67, -0.033)
FwdLauncher.SetPosition2D(66.0, 3.0)
FwdLauncher.SetRepairComplexity(2.0)
FwdLauncher.SetDisabledPercentage(0.2)
FwdLauncher.SetRadius(0.02)
FwdLauncher.SetDumbfire(1)
FwdLauncher.SetWeaponID(0)
FwdLauncher.SetGroups(1)
FwdLauncher.SetDamageRadiusFactor(0.4)
FwdLauncher.SetIconNum(370)
FwdLauncher.SetIconPositionX(61.0)
FwdLauncher.SetIconPositionY(24.0)
FwdLauncher.SetIconAboveShip(1)
FwdLauncher.SetImmediateDelay(2.0)
FwdLauncher.SetReloadDelay(35.0)
FwdLauncher.SetMaxReady(2)
FwdLauncherDirection = App.TGPoint3()
FwdLauncherDirection.SetXYZ(0.0, 1.0, 0.0)
FwdLauncher.SetDirection(FwdLauncherDirection)
FwdLauncherRight = App.TGPoint3()
FwdLauncherRight.SetXYZ(1.0, 0.0, 0.0)
FwdLauncher.SetRight(FwdLauncherRight)
App.g_kModelPropertyManager.RegisterLocalTemplate(FwdLauncher)
#################################################
Hull = App.HullProperty_Create('Hull')
Hull.SetMaxCondition(5500.0)
Hull.SetCritical(1)
Hull.SetTargetable(1)
Hull.SetPrimary(1)
Hull.SetPosition(0.0, -0.25, 0.0)
Hull.SetPosition2D(-2.0, 11.0)
Hull.SetRepairComplexity(2.0)
Hull.SetDisabledPercentage(0.0)
Hull.SetRadius(1.0)
App.g_kModelPropertyManager.RegisterLocalTemplate(Hull)
#################################################
ShieldGenerator = App.ShieldProperty_Create('Shield Generator')
ShieldGenerator.SetMaxCondition(3000.0)
ShieldGenerator.SetCritical(0)
ShieldGenerator.SetTargetable(1)
ShieldGenerator.SetPrimary(1)
ShieldGenerator.SetPosition(0.0, -0.055, 0.0)
ShieldGenerator.SetPosition2D(66.0, 73.0)
ShieldGenerator.SetRepairComplexity(2.0)
ShieldGenerator.SetDisabledPercentage(0.5)
ShieldGenerator.SetRadius(0.04)
ShieldGenerator.SetNormalPowerPerSecond(450.0)
ShieldGeneratorShieldGlowColor = App.TGColorA()
ShieldGeneratorShieldGlowColor.SetRGBA(0.0, 1.0, 0.501961, 0.466667)
ShieldGenerator.SetShieldGlowColor(ShieldGeneratorShieldGlowColor)
ShieldGenerator.SetShieldGlowDecay(1.0)
ShieldGenerator.SetMaxShields(ShieldGenerator.FRONT_SHIELDS, 5000.0)
ShieldGenerator.SetMaxShields(ShieldGenerator.REAR_SHIELDS, 4500.0)
ShieldGenerator.SetMaxShields(ShieldGenerator.TOP_SHIELDS, 4500.0)
ShieldGenerator.SetMaxShields(ShieldGenerator.BOTTOM_SHIELDS, 4500.0)
ShieldGenerator.SetMaxShields(ShieldGenerator.LEFT_SHIELDS, 4500.0)
ShieldGenerator.SetMaxShields(ShieldGenerator.RIGHT_SHIELDS, 4500.0)
ShieldGenerator.SetShieldChargePerSecond(ShieldGenerator.FRONT_SHIELDS, 15.0)
ShieldGenerator.SetShieldChargePerSecond(ShieldGenerator.REAR_SHIELDS, 10.0)
ShieldGenerator.SetShieldChargePerSecond(ShieldGenerator.TOP_SHIELDS, 10.0)
ShieldGenerator.SetShieldChargePerSecond(ShieldGenerator.BOTTOM_SHIELDS, 10.0)
ShieldGenerator.SetShieldChargePerSecond(ShieldGenerator.LEFT_SHIELDS, 10.0)
ShieldGenerator.SetShieldChargePerSecond(ShieldGenerator.RIGHT_SHIELDS, 10.0)
App.g_kModelPropertyManager.RegisterLocalTemplate(ShieldGenerator)
#################################################
SensorArray = App.SensorProperty_Create('Sensor Array')
SensorArray.SetMaxCondition(3000.0)
SensorArray.SetCritical(0)
SensorArray.SetTargetable(1)
SensorArray.SetPrimary(1)
SensorArray.SetPosition(0.0, 0.45, -0.04)
SensorArray.SetPosition2D(64.0, 30.0)
SensorArray.SetRepairComplexity(2.0)
SensorArray.SetDisabledPercentage(0.5)
SensorArray.SetRadius(0.02)
SensorArray.SetNormalPowerPerSecond(450.0)
SensorArray.SetBaseSensorRange(1500.0)
SensorArray.SetMaxProbes(4)
App.g_kModelPropertyManager.RegisterLocalTemplate(SensorArray)
#################################################
WarpCore = App.PowerProperty_Create('Warp Core')
WarpCore.SetMaxCondition(3000.0)
WarpCore.SetCritical(1)
WarpCore.SetTargetable(1)
WarpCore.SetPrimary(1)
WarpCore.SetPosition(0.0, -0.407, -0.028)
WarpCore.SetPosition2D(65.0, 93.0)
WarpCore.SetRepairComplexity(2.0)
WarpCore.SetDisabledPercentage(0.33)
WarpCore.SetRadius(0.05)
WarpCore.SetMainBatteryLimit(200000.0)
WarpCore.SetBackupBatteryLimit(100000.0)
WarpCore.SetMainConduitCapacity(2250.0)
WarpCore.SetBackupConduitCapacity(250.0)
WarpCore.SetPowerOutput(2000.0)
App.g_kModelPropertyManager.RegisterLocalTemplate(WarpCore)
#################################################
ImpulseEngines = App.ImpulseEngineProperty_Create('Impulse Engines')
ImpulseEngines.SetMaxCondition(3000.0)
ImpulseEngines.SetCritical(0)
ImpulseEngines.SetTargetable(0)
ImpulseEngines.SetPrimary(1)
ImpulseEngines.SetPosition(0.0, -0.3, 0.0)
ImpulseEngines.SetPosition2D(78.0, 59.0)
ImpulseEngines.SetRepairComplexity(2.0)
ImpulseEngines.SetDisabledPercentage(0.5)
ImpulseEngines.SetRadius(1.0)
ImpulseEngines.SetNormalPowerPerSecond(450.0)
ImpulseEngines.SetMaxAccel(3.0)
ImpulseEngines.SetMaxAngularAccel(0.5)
ImpulseEngines.SetMaxAngularVelocity(0.5)
ImpulseEngines.SetMaxSpeed(8.5)
ImpulseEngines.SetEngineSound('Klingon Engines')
App.g_kModelPropertyManager.RegisterLocalTemplate(ImpulseEngines)
#################################################
DisruptorCannons = App.WeaponSystemProperty_Create('Disruptor Cannons')
DisruptorCannons.SetMaxCondition(1000.0)
DisruptorCannons.SetCritical(0)
DisruptorCannons.SetTargetable(0)
DisruptorCannons.SetPrimary(1)
DisruptorCannons.SetPosition(0.0, -0.3, 0.0)
DisruptorCannons.SetPosition2D(5.0, 5.0)
DisruptorCannons.SetRepairComplexity(3.0)
DisruptorCannons.SetDisabledPercentage(0.5)
DisruptorCannons.SetRadius(1.0)
DisruptorCannons.SetNormalPowerPerSecond(225.0)
DisruptorCannons.SetWeaponSystemType(DisruptorCannons.WST_PULSE)
DisruptorCannons.SetSingleFire(0)
DisruptorCannons.SetAimedWeapon(0)
kFiringChainString = App.TGString()
kFiringChainString.SetString('')
DisruptorCannons.SetFiringChainString(kFiringChainString)
App.g_kModelPropertyManager.RegisterLocalTemplate(DisruptorCannons)
#################################################
WarpEngines = App.WarpEngineProperty_Create('Warp Engines')
WarpEngines.SetMaxCondition(8000.0)
WarpEngines.SetCritical(0)
WarpEngines.SetTargetable(0)
WarpEngines.SetPrimary(1)
WarpEngines.SetPosition(0.0, -0.3, 0.0)
WarpEngines.SetPosition2D(67.0, 109.0)
WarpEngines.SetRepairComplexity(3.0)
WarpEngines.SetDisabledPercentage(0.5)
WarpEngines.SetRadius(1.0)
WarpEngines.SetNormalPowerPerSecond(1.0)
App.g_kModelPropertyManager.RegisterLocalTemplate(WarpEngines)
#################################################
Torpedoes = App.TorpedoSystemProperty_Create('Torpedoes')
Torpedoes.SetMaxCondition(1000.0)
Torpedoes.SetCritical(0)
Torpedoes.SetTargetable(0)
Torpedoes.SetPrimary(1)
Torpedoes.SetPosition(0.0, -0.3, 0.0)
Torpedoes.SetPosition2D(70.0, 24.0)
Torpedoes.SetRepairComplexity(2.0)
Torpedoes.SetDisabledPercentage(0.5)
Torpedoes.SetRadius(1.0)
Torpedoes.SetNormalPowerPerSecond(225.0)
Torpedoes.SetWeaponSystemType(Torpedoes.WST_TORPEDO)
Torpedoes.SetSingleFire(0)
Torpedoes.SetAimedWeapon(1)
kFiringChainString = App.TGString()
kFiringChainString.SetString('')
Torpedoes.SetFiringChainString(kFiringChainString)
Torpedoes.SetMaxTorpedoes(0, 200)
Torpedoes.SetTorpedoScript(0, 'Tactical.Projectiles.ZZNewKTorp')
Torpedoes.SetNumAmmoTypes(1)
App.g_kModelPropertyManager.RegisterLocalTemplate(Torpedoes)
#################################################
PortWarp = App.EngineProperty_Create('Port Warp')
PortWarp.SetMaxCondition(2000.0)
PortWarp.SetCritical(0)
PortWarp.SetTargetable(1)
PortWarp.SetPrimary(1)
PortWarp.SetPosition(-0.13, -0.51, 0.045)
PortWarp.SetPosition2D(51.0, 104.0)
PortWarp.SetRepairComplexity(2.0)
PortWarp.SetDisabledPercentage(0.5)
PortWarp.SetRadius(0.06)
PortWarp.SetEngineType(PortWarp.EP_WARP)
App.g_kModelPropertyManager.RegisterLocalTemplate(PortWarp)
#################################################
StarWarp = App.EngineProperty_Create('Star Warp')
StarWarp.SetMaxCondition(2000.0)
StarWarp.SetCritical(0)
StarWarp.SetTargetable(1)
StarWarp.SetPrimary(1)
StarWarp.SetPosition(0.13, -0.51, 0.045)
StarWarp.SetPosition2D(77.0, 105.0)
StarWarp.SetRepairComplexity(2.0)
StarWarp.SetDisabledPercentage(0.5)
StarWarp.SetRadius(0.06)
StarWarp.SetEngineType(StarWarp.EP_WARP)
App.g_kModelPropertyManager.RegisterLocalTemplate(StarWarp)
#################################################
DamageControl = App.RepairSubsystemProperty_Create('Damage Control')
DamageControl.SetMaxCondition(1000.0)
DamageControl.SetCritical(0)
DamageControl.SetTargetable(0)
DamageControl.SetPrimary(1)
DamageControl.SetPosition(0.0, -0.3, 0.0)
DamageControl.SetPosition2D(64.0, 123.0)
DamageControl.SetRepairComplexity(3.0)
DamageControl.SetDisabledPercentage(0.1)
DamageControl.SetRadius(1.0)
DamageControl.SetNormalPowerPerSecond(1.0)
DamageControl.SetMaxRepairPoints(40.0)
DamageControl.SetNumRepairTeams(3)
App.g_kModelPropertyManager.RegisterLocalTemplate(DamageControl)
#################################################
Bridge = App.HullProperty_Create('Bridge')
Bridge.SetMaxCondition(3000.0)
Bridge.SetCritical(1)
Bridge.SetTargetable(1)
Bridge.SetPrimary(0)
Bridge.SetPosition(0.015, 0.52, 0.05)
Bridge.SetPosition2D(62.0, 23.0)
Bridge.SetRepairComplexity(1.0)
Bridge.SetDisabledPercentage(0.0)
Bridge.SetRadius(0.02)
App.g_kModelPropertyManager.RegisterLocalTemplate(Bridge)
#################################################
ZZQuD = App.ShipProperty_Create('ZZQuD')
ZZQuD.SetGenus(1)
ZZQuD.SetSpecies(301)
ZZQuD.SetMass(300.0)
ZZQuD.SetRotationalInertia(250.0)
ZZQuD.SetShipName('ZZQuD')
ZZQuD.SetModelFilename('data/Models/Ships/ZZQuD/ZZQuD.nif')
ZZQuD.SetDamageResolution(15.0)
ZZQuD.SetAffiliation(0)
ZZQuD.SetStationary(0)
ZZQuD.SetAIString('NonFedAttack')
ZZQuD.SetDeathExplosionSound('g_lsDeathExplosions')
App.g_kModelPropertyManager.RegisterLocalTemplate(ZZQuD)
#################################################
Tractors = App.WeaponSystemProperty_Create('Tractors')
Tractors.SetMaxCondition(2000.0)
Tractors.SetCritical(0)
Tractors.SetTargetable(0)
Tractors.SetPrimary(1)
Tractors.SetPosition(0.0, -0.3, 0.0)
Tractors.SetPosition2D(64.0, 80.0)
Tractors.SetRepairComplexity(3.0)
Tractors.SetDisabledPercentage(0.5)
Tractors.SetRadius(1.0)
Tractors.SetNormalPowerPerSecond(225.0)
Tractors.SetWeaponSystemType(Tractors.WST_TRACTOR)
Tractors.SetSingleFire(1)
Tractors.SetAimedWeapon(0)
kFiringChainString = App.TGString()
kFiringChainString.SetString('')
Tractors.SetFiringChainString(kFiringChainString)
App.g_kModelPropertyManager.RegisterLocalTemplate(Tractors)
#################################################
AftTractor = App.TractorBeamProperty_Create('Aft Tractor')
AftTractor.SetMaxCondition(1500.0)
AftTractor.SetCritical(0)
AftTractor.SetTargetable(1)
AftTractor.SetPrimary(1)
AftTractor.SetPosition(0.0, -0.49, -0.033)
AftTractor.SetPosition2D(69.0, 118.0)
AftTractor.SetRepairComplexity(2.0)
AftTractor.SetDisabledPercentage(0.5)
AftTractor.SetRadius(0.02)
AftTractor.SetDumbfire(0)
AftTractor.SetWeaponID(0)
AftTractor.SetGroups(0)
AftTractor.SetDamageRadiusFactor(0.2)
AftTractor.SetIconNum(0)
AftTractor.SetIconPositionX(0.0)
AftTractor.SetIconPositionY(0.0)
AftTractor.SetIconAboveShip(1)
AftTractor.SetFireSound('Tractor Beam')
AftTractor.SetMaxCharge(1.0)
AftTractor.SetMaxDamage(60.0)
AftTractor.SetMaxDamageDistance(100.0)
AftTractor.SetMinFiringCharge(1.0)
AftTractor.SetNormalDischargeRate(1.0)
AftTractor.SetRechargeRate(1.0)
AftTractor.SetIndicatorIconNum(0)
AftTractor.SetIndicatorIconPositionX(0.0)
AftTractor.SetIndicatorIconPositionY(0.0)
AftTractorForward = App.TGPoint3()
AftTractorForward.SetXYZ(0.0, -1.0, 0.0)
AftTractorUp = App.TGPoint3()
AftTractorUp.SetXYZ(0.0, 0.0, -1.0)
AftTractor.SetOrientation(AftTractorForward, AftTractorUp)
AftTractor.SetArcWidthAngles(-0.349066, 0.349066)
AftTractor.SetArcHeightAngles(0.0, 0.523599)
AftTractor.SetTractorBeamWidth(0.3)
AftTractor.SetTextureStart(0)
AftTractor.SetTextureEnd(0)
AftTractor.SetTextureName('data/Textures/Tactical/TractorBeam.tga')
kColor = App.TGColorA()
kColor.SetRGBA(0.4, 0.4, 1.0, 1.0)
AftTractor.SetOuterShellColor(kColor)
kColor.SetRGBA(0.4, 0.4, 1.0, 1.0)
AftTractor.SetInnerShellColor(kColor)
kColor.SetRGBA(0.4, 0.4, 1.0, 1.0)
AftTractor.SetOuterCoreColor(kColor)
kColor.SetRGBA(0.4, 0.4, 1.0, 1.0)
AftTractor.SetInnerCoreColor(kColor)
AftTractor.SetNumSides(12)
AftTractor.SetMainRadius(0.075)
AftTractor.SetTaperRadius(0.0)
AftTractor.SetCoreScale(0.3)
AftTractor.SetTaperRatio(0.15)
AftTractor.SetTaperMinLength(1.0)
AftTractor.SetTaperMaxLength(5.0)
AftTractor.SetLengthTextureTilePerUnit(0.25)
AftTractor.SetPerimeterTile(1.0)
AftTractor.SetTextureSpeed(0.2)
AftTractor.SetTextureName('data/Textures/Tactical/TractorBeam.tga')
App.g_kModelPropertyManager.RegisterLocalTemplate(AftTractor)
#################################################
FwdTractor = App.TractorBeamProperty_Create('Fwd Tractor')
FwdTractor.SetMaxCondition(1500.0)
FwdTractor.SetCritical(0)
FwdTractor.SetTargetable(1)
FwdTractor.SetPrimary(1)
FwdTractor.SetPosition(0.0, 0.72, 0.0)
FwdTractor.SetPosition2D(52.0, 13.0)
FwdTractor.SetRepairComplexity(2.0)
FwdTractor.SetDisabledPercentage(0.5)
FwdTractor.SetRadius(0.01)
FwdTractor.SetDumbfire(0)
FwdTractor.SetWeaponID(0)
FwdTractor.SetGroups(0)
FwdTractor.SetDamageRadiusFactor(0.2)
FwdTractor.SetIconNum(0)
FwdTractor.SetIconPositionX(0.0)
FwdTractor.SetIconPositionY(0.0)
FwdTractor.SetIconAboveShip(1)
FwdTractor.SetFireSound('Tractor Beam')
FwdTractor.SetMaxCharge(1.0)
FwdTractor.SetMaxDamage(60.0)
FwdTractor.SetMaxDamageDistance(100.0)
FwdTractor.SetMinFiringCharge(1.0)
FwdTractor.SetNormalDischargeRate(1.0)
FwdTractor.SetRechargeRate(1.0)
FwdTractor.SetIndicatorIconNum(0)
FwdTractor.SetIndicatorIconPositionX(0.0)
FwdTractor.SetIndicatorIconPositionY(0.0)
FwdTractorForward = App.TGPoint3()
FwdTractorForward.SetXYZ(0.0, 0.995037, -0.099504)
FwdTractorUp = App.TGPoint3()
FwdTractorUp.SetXYZ(0.0, 0.0, 1.0)
FwdTractor.SetOrientation(FwdTractorForward, FwdTractorUp)
FwdTractor.SetArcWidthAngles(-0.349066, 0.349066)
FwdTractor.SetArcHeightAngles(-0.349066, 0.349066)
FwdTractor.SetTractorBeamWidth(0.3)
FwdTractor.SetTextureStart(0)
FwdTractor.SetTextureEnd(0)
FwdTractor.SetTextureName('data/Textures/Tactical/TractorBeam.tga')
kColor = App.TGColorA()
kColor.SetRGBA(0.4, 0.4, 1.0, 1.0)
FwdTractor.SetOuterShellColor(kColor)
kColor.SetRGBA(0.4, 0.4, 1.0, 1.0)
FwdTractor.SetInnerShellColor(kColor)
kColor.SetRGBA(0.4, 0.4, 1.0, 1.0)
FwdTractor.SetOuterCoreColor(kColor)
kColor.SetRGBA(0.4, 0.4, 1.0, 1.0)
FwdTractor.SetInnerCoreColor(kColor)
FwdTractor.SetNumSides(12)
FwdTractor.SetMainRadius(0.075)
FwdTractor.SetTaperRadius(0.0)
FwdTractor.SetCoreScale(0.3)
FwdTractor.SetTaperRatio(0.15)
FwdTractor.SetTaperMinLength(1.0)
FwdTractor.SetTaperMaxLength(5.0)
FwdTractor.SetLengthTextureTilePerUnit(0.25)
FwdTractor.SetPerimeterTile(1.0)
FwdTractor.SetTextureSpeed(0.2)
FwdTractor.SetTextureName('data/Textures/Tactical/TractorBeam.tga')
App.g_kModelPropertyManager.RegisterLocalTemplate(FwdTractor)
#################################################
ViewscreenForward = App.PositionOrientationProperty_Create('ViewscreenForward')
ViewscreenForwardForward = App.TGPoint3()
ViewscreenForwardForward.SetXYZ(0.0, 1.0, 0.0)
ViewscreenForwardUp = App.TGPoint3()
ViewscreenForwardUp.SetXYZ(0.0, 0.0, 1.0)
ViewscreenForwardRight = App.TGPoint3()
ViewscreenForwardRight.SetXYZ(1.0, 0.0, 0.0)
ViewscreenForward.SetOrientation(ViewscreenForwardForward, ViewscreenForwardUp, ViewscreenForwardRight)
ViewscreenForwardPosition = App.TGPoint3()
ViewscreenForwardPosition.SetXYZ(0.0, 0.8, 0.0)
ViewscreenForward.SetPosition(ViewscreenForwardPosition)
App.g_kModelPropertyManager.RegisterLocalTemplate(ViewscreenForward)
#################################################
ViewscreenLeft = App.PositionOrientationProperty_Create('ViewscreenLeft')
ViewscreenLeftForward = App.TGPoint3()
ViewscreenLeftForward.SetXYZ(-1.0, 0.0, 0.0)
ViewscreenLeftUp = App.TGPoint3()
ViewscreenLeftUp.SetXYZ(0.0, 0.0, 1.0)
ViewscreenLeftRight = App.TGPoint3()
ViewscreenLeftRight.SetXYZ(0.0, 1.0, 0.0)
ViewscreenLeft.SetOrientation(ViewscreenLeftForward, ViewscreenLeftUp, ViewscreenLeftRight)
ViewscreenLeftPosition = App.TGPoint3()
ViewscreenLeftPosition.SetXYZ(-0.6, 0.0, 0.0)
ViewscreenLeft.SetPosition(ViewscreenLeftPosition)
App.g_kModelPropertyManager.RegisterLocalTemplate(ViewscreenLeft)
#################################################
ViewscreenRight = App.PositionOrientationProperty_Create('ViewscreenRight')
ViewscreenRightForward = App.TGPoint3()
ViewscreenRightForward.SetXYZ(1.0, 0.0, 0.0)
ViewscreenRightUp = App.TGPoint3()
ViewscreenRightUp.SetXYZ(0.0, 0.0, 1.0)
ViewscreenRightRight = App.TGPoint3()
ViewscreenRightRight.SetXYZ(0.0, -1.0, 0.0)
ViewscreenRight.SetOrientation(ViewscreenRightForward, ViewscreenRightUp, ViewscreenRightRight)
ViewscreenRightPosition = App.TGPoint3()
ViewscreenRightPosition.SetXYZ(0.6, 0.0, 0.0)
ViewscreenRight.SetPosition(ViewscreenRightPosition)
App.g_kModelPropertyManager.RegisterLocalTemplate(ViewscreenRight)
#################################################
ViewscreenBack = App.PositionOrientationProperty_Create('ViewscreenBack')
ViewscreenBackForward = App.TGPoint3()
ViewscreenBackForward.SetXYZ(0.0, -1.0, 0.0)
ViewscreenBackUp = App.TGPoint3()
ViewscreenBackUp.SetXYZ(0.0, 0.0, 1.0)
ViewscreenBackRight = App.TGPoint3()
ViewscreenBackRight.SetXYZ(-1.0, 0.0, 0.0)
ViewscreenBack.SetOrientation(ViewscreenBackForward, ViewscreenBackUp, ViewscreenBackRight)
ViewscreenBackPosition = App.TGPoint3()
ViewscreenBackPosition.SetXYZ(0.0, -0.7, 0.0)
ViewscreenBack.SetPosition(ViewscreenBackPosition)
App.g_kModelPropertyManager.RegisterLocalTemplate(ViewscreenBack)
#################################################
ViewscreenUp = App.PositionOrientationProperty_Create('ViewscreenUp')
ViewscreenUpForward = App.TGPoint3()
ViewscreenUpForward.SetXYZ(0.0, 0.0, 1.0)
ViewscreenUpUp = App.TGPoint3()
ViewscreenUpUp.SetXYZ(0.0, -1.0, 0.0)
ViewscreenUpRight = App.TGPoint3()
ViewscreenUpRight.SetXYZ(1.0, 0.0, 0.0)
ViewscreenUp.SetOrientation(ViewscreenUpForward, ViewscreenUpUp, ViewscreenUpRight)
ViewscreenUpPosition = App.TGPoint3()
ViewscreenUpPosition.SetXYZ(0.0, 0.0, 0.2)
ViewscreenUp.SetPosition(ViewscreenUpPosition)
App.g_kModelPropertyManager.RegisterLocalTemplate(ViewscreenUp)
#################################################
ViewscreenDown = App.PositionOrientationProperty_Create('ViewscreenDown')
ViewscreenDownForward = App.TGPoint3()
ViewscreenDownForward.SetXYZ(0.0, 0.0, -1.0)
ViewscreenDownUp = App.TGPoint3()
ViewscreenDownUp.SetXYZ(0.0, 1.0, 0.0)
ViewscreenDownRight = App.TGPoint3()
ViewscreenDownRight.SetXYZ(1.0, 0.0, 0.0)
ViewscreenDown.SetOrientation(ViewscreenDownForward, ViewscreenDownUp, ViewscreenDownRight)
ViewscreenDownPosition = App.TGPoint3()
ViewscreenDownPosition.SetXYZ(0.0, 0.0, -0.2)
ViewscreenDown.SetPosition(ViewscreenDownPosition)
App.g_kModelPropertyManager.RegisterLocalTemplate(ViewscreenDown)
#################################################
FirstPersonCamera = App.PositionOrientationProperty_Create('FirstPersonCamera')
FirstPersonCameraForward = App.TGPoint3()
FirstPersonCameraForward.SetXYZ(0.0, 1.0, 0.0)
FirstPersonCameraUp = App.TGPoint3()
FirstPersonCameraUp.SetXYZ(0.0, 0.0, 1.0)
FirstPersonCameraRight = App.TGPoint3()
FirstPersonCameraRight.SetXYZ(1.0, 0.0, 0.0)
FirstPersonCamera.SetOrientation(FirstPersonCameraForward, FirstPersonCameraUp, FirstPersonCameraRight)
FirstPersonCameraPosition = App.TGPoint3()
FirstPersonCameraPosition.SetXYZ(0.02, 0.6, 0.045)
FirstPersonCamera.SetPosition(FirstPersonCameraPosition)
App.g_kModelPropertyManager.RegisterLocalTemplate(FirstPersonCamera)
#################################################
Impulse = App.EngineProperty_Create('Impulse')
Impulse.SetMaxCondition(2500.0)
Impulse.SetCritical(0)
Impulse.SetTargetable(1)
Impulse.SetPrimary(1)
Impulse.SetPosition(0.0, -0.6, 0.0)
Impulse.SetPosition2D(63.0, 110.0)
Impulse.SetRepairComplexity(2.0)
Impulse.SetDisabledPercentage(0.25)
Impulse.SetRadius(0.1)
Impulse.SetEngineType(Impulse.EP_IMPULSE)
App.g_kModelPropertyManager.RegisterLocalTemplate(Impulse)
#################################################
CloakingDevice = App.CloakingSubsystemProperty_Create('Cloaking Device')
CloakingDevice.SetMaxCondition(2500.0)
CloakingDevice.SetCritical(0)
CloakingDevice.SetTargetable(1)
CloakingDevice.SetPrimary(1)
CloakingDevice.SetPosition(0.0, 0.38, 0.02)
CloakingDevice.SetPosition2D(62.0, 53.0)
CloakingDevice.SetRepairComplexity(2.0)
CloakingDevice.SetDisabledPercentage(0.33)
CloakingDevice.SetRadius(0.04)
CloakingDevice.SetNormalPowerPerSecond(225.0)
CloakingDevice.SetCloakStrength(300.0)
App.g_kModelPropertyManager.RegisterLocalTemplate(CloakingDevice)
#################################################
FwdPortWing = App.PulseWeaponProperty_Create('Fwd Port Wing')
FwdPortWing.SetMaxCondition(2500.0)
FwdPortWing.SetCritical(0)
FwdPortWing.SetTargetable(1)
FwdPortWing.SetPrimary(1)
FwdPortWing.SetPosition(-0.77, 0.106, -0.415)
FwdPortWing.SetPosition2D(4.0, 45.0)
FwdPortWing.SetRepairComplexity(2.0)
FwdPortWing.SetDisabledPercentage(0.33)
FwdPortWing.SetRadius(0.02)
FwdPortWing.SetDumbfire(1)
FwdPortWing.SetWeaponID(1)
FwdPortWing.SetGroups(0)
FwdPortWing.SetDamageRadiusFactor(0.03)
FwdPortWing.SetIconNum(365)
FwdPortWing.SetIconPositionX(32.0)
FwdPortWing.SetIconPositionY(63.0)
FwdPortWing.SetIconAboveShip(1)
FwdPortWing.SetFireSound('Klingon Disruptor')
FwdPortWing.SetMaxCharge(4.0)
FwdPortWing.SetMaxDamage(1.0)
FwdPortWing.SetMaxDamageDistance(100.0)
FwdPortWing.SetMinFiringCharge(2.0)
FwdPortWing.SetNormalDischargeRate(1.0)
FwdPortWing.SetRechargeRate(0.25)
FwdPortWing.SetIndicatorIconNum(0)
FwdPortWing.SetIndicatorIconPositionX(24.0)
FwdPortWing.SetIndicatorIconPositionY(67.0)
FwdPortWingForward = App.TGPoint3()
FwdPortWingForward.SetXYZ(0.0, 1.0, 0.0)
FwdPortWingUp = App.TGPoint3()
FwdPortWingUp.SetXYZ(0.0, 0.0, 1.0)
FwdPortWing.SetOrientation(FwdPortWingForward, FwdPortWingUp)
FwdPortWing.SetArcWidthAngles(-0.349066, 0.349066)
FwdPortWing.SetArcHeightAngles(-0.349066, 0.349066)
FwdPortWing.SetCooldownTime(0.1)
FwdPortWing.SetModuleName('Tactical.Projectiles.ZZ_QuDHeavyD')
App.g_kModelPropertyManager.RegisterLocalTemplate(FwdPortWing)
#################################################
FwdStarWing = App.PulseWeaponProperty_Create('Fwd Star Wing')
FwdStarWing.SetMaxCondition(2500.0)
FwdStarWing.SetCritical(0)
FwdStarWing.SetTargetable(1)
FwdStarWing.SetPrimary(1)
FwdStarWing.SetPosition(0.77, 0.106, -0.415)
FwdStarWing.SetPosition2D(121.0, 47.0)
FwdStarWing.SetRepairComplexity(2.0)
FwdStarWing.SetDisabledPercentage(0.33)
FwdStarWing.SetRadius(0.02)
FwdStarWing.SetDumbfire(1)
FwdStarWing.SetWeaponID(1)
FwdStarWing.SetGroups(0)
FwdStarWing.SetDamageRadiusFactor(0.03)
FwdStarWing.SetIconNum(365)
FwdStarWing.SetIconPositionX(92.0)
FwdStarWing.SetIconPositionY(63.0)
FwdStarWing.SetIconAboveShip(1)
FwdStarWing.SetFireSound('')
FwdStarWing.SetMaxCharge(4.0)
FwdStarWing.SetMaxDamage(1.0)
FwdStarWing.SetMaxDamageDistance(100.0)
FwdStarWing.SetMinFiringCharge(2.0)
FwdStarWing.SetNormalDischargeRate(1.0)
FwdStarWing.SetRechargeRate(0.25)
FwdStarWing.SetIndicatorIconNum(0)
FwdStarWing.SetIndicatorIconPositionX(104.0)
FwdStarWing.SetIndicatorIconPositionY(67.0)
FwdStarWingForward = App.TGPoint3()
FwdStarWingForward.SetXYZ(0.0, 1.0, 0.0)
FwdStarWingUp = App.TGPoint3()
FwdStarWingUp.SetXYZ(0.0, 0.0, 1.0)
FwdStarWing.SetOrientation(FwdStarWingForward, FwdStarWingUp)
FwdStarWing.SetArcWidthAngles(-0.349066, 0.349066)
FwdStarWing.SetArcHeightAngles(-0.349066, 0.349066)
FwdStarWing.SetCooldownTime(0.1)
FwdStarWing.SetModuleName('Tactical.Projectiles.ZZ_QuDHeavyD')
App.g_kModelPropertyManager.RegisterLocalTemplate(FwdStarWing)
#################################################
FwdPort = App.PulseWeaponProperty_Create('Fwd Port')
FwdPort.SetMaxCondition(2500.0)
FwdPort.SetCritical(0)
FwdPort.SetTargetable(1)
FwdPort.SetPrimary(1)
FwdPort.SetPosition(-0.212, -0.087, -0.073)
FwdPort.SetPosition2D(45.0, 59.0)
FwdPort.SetRepairComplexity(2.0)
FwdPort.SetDisabledPercentage(0.33)
FwdPort.SetRadius(0.03)
FwdPort.SetDumbfire(1)
FwdPort.SetWeaponID(1)
FwdPort.SetGroups(0)
FwdPort.SetDamageRadiusFactor(0.03)
FwdPort.SetIconNum(365)
FwdPort.SetIconPositionX(52.0)
FwdPort.SetIconPositionY(73.0)
FwdPort.SetIconAboveShip(1)
FwdPort.SetFireSound('')
FwdPort.SetMaxCharge(4.0)
FwdPort.SetMaxDamage(1.0)
FwdPort.SetMaxDamageDistance(100.0)
FwdPort.SetMinFiringCharge(2.0)
FwdPort.SetNormalDischargeRate(1.0)
FwdPort.SetRechargeRate(0.33)
FwdPort.SetIndicatorIconNum(0)
FwdPort.SetIndicatorIconPositionX(44.0)
FwdPort.SetIndicatorIconPositionY(77.0)
FwdPortForward = App.TGPoint3()
FwdPortForward.SetXYZ(0.0, 1.0, 0.0)
FwdPortUp = App.TGPoint3()
FwdPortUp.SetXYZ(0.0, 0.0, 1.0)
FwdPort.SetOrientation(FwdPortForward, FwdPortUp)
FwdPort.SetArcWidthAngles(-0.349066, 0.349066)
FwdPort.SetArcHeightAngles(-0.349066, 0.349066)
FwdPort.SetCooldownTime(0.1)
FwdPort.SetModuleName('Tactical.Projectiles.ZZ_QuDD')
App.g_kModelPropertyManager.RegisterLocalTemplate(FwdPort)
#################################################
FwdStar = App.PulseWeaponProperty_Create('Fwd Star')
FwdStar.SetMaxCondition(2500.0)
FwdStar.SetCritical(0)
FwdStar.SetTargetable(1)
FwdStar.SetPrimary(1)
FwdStar.SetPosition(0.212, -0.087, -0.073)
FwdStar.SetPosition2D(80.0, 60.0)
FwdStar.SetRepairComplexity(32.0)
FwdStar.SetDisabledPercentage(0.33)
FwdStar.SetRadius(0.03)
FwdStar.SetDumbfire(1)
FwdStar.SetWeaponID(1)
FwdStar.SetGroups(0)
FwdStar.SetDamageRadiusFactor(0.03)
FwdStar.SetIconNum(365)
FwdStar.SetIconPositionX(72.0)
FwdStar.SetIconPositionY(73.0)
FwdStar.SetIconAboveShip(1)
FwdStar.SetFireSound('')
FwdStar.SetMaxCharge(4.0)
FwdStar.SetMaxDamage(1.0)
FwdStar.SetMaxDamageDistance(100.0)
FwdStar.SetMinFiringCharge(2.0)
FwdStar.SetNormalDischargeRate(1.0)
FwdStar.SetRechargeRate(0.33)
FwdStar.SetIndicatorIconNum(0)
FwdStar.SetIndicatorIconPositionX(84.0)
FwdStar.SetIndicatorIconPositionY(77.0)
FwdStarForward = App.TGPoint3()
FwdStarForward.SetXYZ(0.0, 1.0, 0.0)
FwdStarUp = App.TGPoint3()
FwdStarUp.SetXYZ(0.0, 0.0, 1.0)
FwdStar.SetOrientation(FwdStarForward, FwdStarUp)
FwdStar.SetArcWidthAngles(-0.349066, 0.349066)
FwdStar.SetArcHeightAngles(-0.349066, 0.349066)
FwdStar.SetCooldownTime(0.1)
FwdStar.SetModuleName('Tactical.Projectiles.ZZ_QuDD')
App.g_kModelPropertyManager.RegisterLocalTemplate(FwdStar)
#################################################
FMPACannon = App.PulseWeaponProperty_Create('FMPA Cannon')
FMPACannon.SetMaxCondition(2500.0)
FMPACannon.SetCritical(0)
FMPACannon.SetTargetable(1)
FMPACannon.SetPrimary(1)
FMPACannon.SetPosition(0.0, -0.2, 0.129)
FMPACannon.SetPosition2D(62.0, 62.0)
FMPACannon.SetRepairComplexity(2.0)
FMPACannon.SetDisabledPercentage(0.3)
FMPACannon.SetRadius(0.02)
FMPACannon.SetDumbfire(1)
FMPACannon.SetWeaponID(1)
FMPACannon.SetGroups(0)
FMPACannon.SetDamageRadiusFactor(0.03)
FMPACannon.SetIconNum(365)
FMPACannon.SetIconPositionX(62.0)
FMPACannon.SetIconPositionY(38.0)
FMPACannon.SetIconAboveShip(1)
FMPACannon.SetFireSound('')
FMPACannon.SetMaxCharge(1.0)
FMPACannon.SetMaxDamage(0.0001)
FMPACannon.SetMaxDamageDistance(100.0)
FMPACannon.SetMinFiringCharge(1.0)
FMPACannon.SetNormalDischargeRate(1.0)
FMPACannon.SetRechargeRate(0.0499)
FMPACannon.SetIndicatorIconNum(0)
FMPACannon.SetIndicatorIconPositionX(64.0)
FMPACannon.SetIndicatorIconPositionY(42.0)
FMPACannonForward = App.TGPoint3()
FMPACannonForward.SetXYZ(0.0, 1.0, 0.0)
FMPACannonUp = App.TGPoint3()
FMPACannonUp.SetXYZ(0.0, 0.0, 1.0)
FMPACannon.SetOrientation(FMPACannonForward, FMPACannonUp)
FMPACannon.SetArcWidthAngles(-0.349066, 0.349066)
FMPACannon.SetArcHeightAngles(-0.349066, 0.349066)
FMPACannon.SetCooldownTime(20.0)
FMPACannon.SetModuleName('Tactical.Projectiles.ZZ_QuDFMPA')
App.g_kModelPropertyManager.RegisterLocalTemplate(FMPACannon)
#################################################
ShuttleBay = App.HullProperty_Create('Shuttle Bay')
ShuttleBay.SetMaxCondition(2000.0)
ShuttleBay.SetCritical(0)
ShuttleBay.SetTargetable(1)
ShuttleBay.SetPrimary(0)
ShuttleBay.SetPosition(0.0, -0.47, 0.07)
ShuttleBay.SetPosition2D(0.0, 0.0)
ShuttleBay.SetRepairComplexity(2.0)
ShuttleBay.SetDisabledPercentage(0.33)
ShuttleBay.SetRadius(0.07)
App.g_kModelPropertyManager.RegisterLocalTemplate(ShuttleBay)
#################################################
ShuttleBayOEP = App.ObjectEmitterProperty_Create('Shuttle Bay OEP')
ShuttleBayOEPForward = App.TGPoint3()
ShuttleBayOEPForward.SetXYZ(0.0, -1.0, 0.0)
ShuttleBayOEPUp = App.TGPoint3()
ShuttleBayOEPUp.SetXYZ(0.0, 0.0, 1.0)
ShuttleBayOEPRight = App.TGPoint3()
ShuttleBayOEPRight.SetXYZ(1.0, 0.0, 0.0)
ShuttleBayOEP.SetOrientation(ShuttleBayOEPForward, ShuttleBayOEPUp, ShuttleBayOEPRight)
ShuttleBayOEPPosition = App.TGPoint3()
ShuttleBayOEPPosition.SetXYZ(0.0, -0.47, 0.07)
ShuttleBayOEP.SetPosition(ShuttleBayOEPPosition)
ShuttleBayOEP.SetEmittedObjectType(ShuttleBayOEP.OEP_SHUTTLE)
App.g_kModelPropertyManager.RegisterLocalTemplate(ShuttleBayOEP)

def LoadPropertySet(pObj):
    """Sets up the object's properties."""
    prop = App.g_kModelPropertyManager.FindByName('ZZQuD', App.TGModelPropertyManager.LOCAL_TEMPLATES)
    if prop != None:
        pObj.AddToSet('Scene Root', prop)
    
    prop = App.g_kModelPropertyManager.FindByName('Hull', App.TGModelPropertyManager.LOCAL_TEMPLATES)
    if prop != None:
        pObj.AddToSet('Scene Root', prop)
    
    prop = App.g_kModelPropertyManager.FindByName('Warp Core', App.TGModelPropertyManager.LOCAL_TEMPLATES)
    if prop != None:
        pObj.AddToSet('Scene Root', prop)
    
    prop = App.g_kModelPropertyManager.FindByName('Shield Generator', App.TGModelPropertyManager.LOCAL_TEMPLATES)
    if prop != None:
        pObj.AddToSet('Scene Root', prop)
    
    prop = App.g_kModelPropertyManager.FindByName('Sensor Array', App.TGModelPropertyManager.LOCAL_TEMPLATES)
    if prop != None:
        pObj.AddToSet('Scene Root', prop)
    
    prop = App.g_kModelPropertyManager.FindByName('Impulse Engines', App.TGModelPropertyManager.LOCAL_TEMPLATES)
    if prop != None:
        pObj.AddToSet('Scene Root', prop)
    
    prop = App.g_kModelPropertyManager.FindByName('Damage Control', App.TGModelPropertyManager.LOCAL_TEMPLATES)
    if prop != None:
        pObj.AddToSet('Scene Root', prop)
    
    prop = App.g_kModelPropertyManager.FindByName('Bridge', App.TGModelPropertyManager.LOCAL_TEMPLATES)
    if prop != None:
        pObj.AddToSet('Scene Root', prop)
    
    prop = App.g_kModelPropertyManager.FindByName('ViewscreenForward', App.TGModelPropertyManager.LOCAL_TEMPLATES)
    if prop != None:
        pObj.AddToSet('Scene Root', prop)
    
    prop = App.g_kModelPropertyManager.FindByName('ViewscreenLeft', App.TGModelPropertyManager.LOCAL_TEMPLATES)
    if prop != None:
        pObj.AddToSet('Scene Root', prop)
    
    prop = App.g_kModelPropertyManager.FindByName('ViewscreenRight', App.TGModelPropertyManager.LOCAL_TEMPLATES)
    if prop != None:
        pObj.AddToSet('Scene Root', prop)
    
    prop = App.g_kModelPropertyManager.FindByName('ViewscreenBack', App.TGModelPropertyManager.LOCAL_TEMPLATES)
    if prop != None:
        pObj.AddToSet('Scene Root', prop)
    
    prop = App.g_kModelPropertyManager.FindByName('ViewscreenUp', App.TGModelPropertyManager.LOCAL_TEMPLATES)
    if prop != None:
        pObj.AddToSet('Scene Root', prop)
    
    prop = App.g_kModelPropertyManager.FindByName('ViewscreenDown', App.TGModelPropertyManager.LOCAL_TEMPLATES)
    if prop != None:
        pObj.AddToSet('Scene Root', prop)
    
    prop = App.g_kModelPropertyManager.FindByName('FirstPersonCamera', App.TGModelPropertyManager.LOCAL_TEMPLATES)
    if prop != None:
        pObj.AddToSet('Scene Root', prop)
    
    prop = App.g_kModelPropertyManager.FindByName('Tractors', App.TGModelPropertyManager.LOCAL_TEMPLATES)
    if prop != None:
        pObj.AddToSet('Scene Root', prop)
    
    prop = App.g_kModelPropertyManager.FindByName('Fwd Tractor', App.TGModelPropertyManager.LOCAL_TEMPLATES)
    if prop != None:
        pObj.AddToSet('Scene Root', prop)
    
    prop = App.g_kModelPropertyManager.FindByName('Aft Tractor', App.TGModelPropertyManager.LOCAL_TEMPLATES)
    if prop != None:
        pObj.AddToSet('Scene Root', prop)
    
    prop = App.g_kModelPropertyManager.FindByName('Warp Engines', App.TGModelPropertyManager.LOCAL_TEMPLATES)
    if prop != None:
        pObj.AddToSet('Scene Root', prop)
    
    prop = App.g_kModelPropertyManager.FindByName('Port Warp', App.TGModelPropertyManager.LOCAL_TEMPLATES)
    if prop != None:
        pObj.AddToSet('Scene Root', prop)
    
    prop = App.g_kModelPropertyManager.FindByName('Star Warp', App.TGModelPropertyManager.LOCAL_TEMPLATES)
    if prop != None:
        pObj.AddToSet('Scene Root', prop)
    
    prop = App.g_kModelPropertyManager.FindByName('Disruptor Cannons', App.TGModelPropertyManager.LOCAL_TEMPLATES)
    if prop != None:
        pObj.AddToSet('Scene Root', prop)
    
    prop = App.g_kModelPropertyManager.FindByName('Torpedoes', App.TGModelPropertyManager.LOCAL_TEMPLATES)
    if prop != None:
        pObj.AddToSet('Scene Root', prop)
    
    prop = App.g_kModelPropertyManager.FindByName('Fwd Launcher', App.TGModelPropertyManager.LOCAL_TEMPLATES)
    if prop != None:
        pObj.AddToSet('Scene Root', prop)
    
    prop = App.g_kModelPropertyManager.FindByName('Impulse', App.TGModelPropertyManager.LOCAL_TEMPLATES)
    if prop != None:
        pObj.AddToSet('Scene Root', prop)
    
    prop = App.g_kModelPropertyManager.FindByName('Cloaking Device', App.TGModelPropertyManager.LOCAL_TEMPLATES)
    if prop != None:
        pObj.AddToSet('Scene Root', prop)
    
    prop = App.g_kModelPropertyManager.FindByName('Fwd Port Wing', App.TGModelPropertyManager.LOCAL_TEMPLATES)
    if prop != None:
        pObj.AddToSet('Scene Root', prop)
    
    prop = App.g_kModelPropertyManager.FindByName('Fwd Star Wing', App.TGModelPropertyManager.LOCAL_TEMPLATES)
    if prop != None:
        pObj.AddToSet('Scene Root', prop)
    
    prop = App.g_kModelPropertyManager.FindByName('Fwd Port', App.TGModelPropertyManager.LOCAL_TEMPLATES)
    if prop != None:
        pObj.AddToSet('Scene Root', prop)
    
    prop = App.g_kModelPropertyManager.FindByName('Fwd Star', App.TGModelPropertyManager.LOCAL_TEMPLATES)
    if prop != None:
        pObj.AddToSet('Scene Root', prop)
    
    prop = App.g_kModelPropertyManager.FindByName('FMPA Cannon', App.TGModelPropertyManager.LOCAL_TEMPLATES)
    if prop != None:
        pObj.AddToSet('Scene Root', prop)
    
    prop = App.g_kModelPropertyManager.FindByName('Shuttle Bay', App.TGModelPropertyManager.LOCAL_TEMPLATES)
    if prop != None:
        pObj.AddToSet('Scene Root', prop)
    
    prop = App.g_kModelPropertyManager.FindByName('Shuttle Bay OEP', App.TGModelPropertyManager.LOCAL_TEMPLATES)
    if prop != None:
        pObj.AddToSet('Scene Root', prop)
    

