# File generated by the Config Library from MLeo Daalder
# Edit on own accord!

config = {
"""Disable WalkFX Sitdown Manager""": 0,
"""Debug Mode""": 1,
"""Disable Extra Models""": 0,
"""Disable Animated Maps""": 0,
"""Disable Bridge Sounds""": 1,
}
