# File generated by the Config Library from MLeo Daalder
# Edit on own accord!

config = {
"""Debug Mode""": 1,
"""Space Muted2""": 0,
"""Disable Animated Maps""": 0,
"""Hull Impact""": 0,
"""Disable Extra Models""": 0,
"""Disable WalkFX Sitdown Manager""": 0,
}
