# Do not Edit this file, Jumpspace uses it to store data

JumpspaceDrive1 = 100.0
JumpspaceDrive2 = 100.0
JumpspaceDrive3 = 0.0
JumpspaceDrive4 = 0.0
JumpspaceDrive5 = 0.0
JumpspaceDrive6 = 0.0
JumpspaceDrive7 = 0.0
JumpspaceDrive8 = 0.0
JumpspaceDrive9 = 0.0
JumpspaceDrive10 = 0.0
JumpspaceDrive11 = 0.0
JumpspaceDrive12 = 0.0
JumpspaceDrive13 = 0.0
JumpspaceDrive14 = 0.0
JumpspaceDrive15 = 0.0
JumpspaceDrive16 = 0.0
JumpspaceDrive17 = 0.0
JumpspaceDrive18 = 0.0
JumpspaceDrive19 = 0.0
JumpspaceDrive20 = 0.0