# Do not Edit this file, Warpspace uses it to store data

WarpspaceDrive1 = 100.0
WarpspaceDrive2 = 100.0
WarpspaceDrive3 = 0.0
WarpspaceDrive4 = 0.0
WarpspaceDrive5 = 0.0
WarpspaceDrive6 = 0.0
WarpspaceDrive7 = 0.0
WarpspaceDrive8 = 0.0
WarpspaceDrive9 = 0.0
WarpspaceDrive10 = 0.0
WarpspaceDrive11 = 0.0
WarpspaceDrive12 = 0.0
WarpspaceDrive13 = 0.0
WarpspaceDrive14 = 0.0
WarpspaceDrive15 = 0.0
WarpspaceDrive16 = 0.0
WarpspaceDrive17 = 0.0
WarpspaceDrive18 = 0.0
WarpspaceDrive19 = 0.0
WarpspaceDrive20 = 0.0