# Standard Music List

dMusic = {"DS9FXDS9Music" : "sfx/Custom/DS9FX/DS9Music.mp3",
          "DS9FXDS9MusicAlternate" : "sfx/Custom/DS9FX/DS9MusicAlternate.mp3",
          "DS9FXDS9Music2" : "sfx/Custom/DS9FX/DS9Music2.mp3",
          "DS9FXWormholeMusic" : "sfx/Custom/DS9FX/WormholeMusic.mp3",
          "DS9FXWormholeMusicAlternate" : "sfx/Custom/DS9FX/WormholeMusicAlternate.mp3",
          "DS9FXGammaMusic" : "sfx/Custom/DS9FX/GammaMusic.mp3",
          "DS9FXGammaMusicAlternate" : "sfx/Custom/DS9FX/GammaMusicAlternate.mp3",
          "DS9FXBadlandsAlternate2" : "sfx/Custom/DS9FX/BadlandsAlternate2.mp3",
          "DS9FXBadlandsAlternate" : "sfx/Custom/DS9FX/BadlandsAlternate1.mp3",
          "DS9FXKaremmaMusic2" : "sfx/Custom/DS9FX/KaremmaMusic2.mp3",
          "DS9FXKaremmaMusic" : "sfx/Custom/DS9FX/KaremmaMusic.mp3",
          "DS9FXDosiMusic2" : "sfx/Custom/DS9FX/DosiMusic2.mp3",
          "DS9FXDosiMusic" : "sfx/Custom/DS9FX/DosiMusic1.mp3",          
          "DS9FXYaderaMusic2" : "sfx/Custom/DS9FX/YaderaMusic2.mp3",
          "DS9FXYaderaMusic" : "sfx/Custom/DS9FX/YaderaMusic.mp3",
          "DS9FXNewBajorMusic1" : "sfx/Custom/DS9FX/NewBajorMusic1.mp3",
          "DS9FXNewBajorMusic2" : "sfx/Custom/DS9FX/NewBajorMusic2.mp3",
          "DS9FXGaiaMusic" : "sfx/Custom/DS9FX/GaiaMusic.mp3",
          "DS9FXGaiaMusic2" : "sfx/Custom/DS9FX/GaiaMusic2.mp3",
          "DS9FXKurrillMusic1" : "sfx/Custom/DS9FX/KurrillMusic1.mp3",
          "DS9FXKurrillMusic2" : "sfx/Custom/DS9FX/KurrillMusic2.mp3",
          "DS9FXMeridianMusic1" : "sfx/Custom/DS9FX/MeridianMusic1.mp3",
          "DS9FXMeridianMusic2" : "sfx/Custom/DS9FX/MeridianMusic2.mp3",
          "DS9FXT-RogoranMusic1" : "sfx/Custom/DS9FX/T-RogoranMusic1.mp3",
          "DS9FXT-RogoranMusic2" : "sfx/Custom/DS9FX/T-RogoranMusic2.mp3",
          "DS9FXVandrosMusic1" : "sfx/Custom/DS9FX/VandrosMusic1.mp3",
          "DS9FXVandrosMusic2" : "sfx/Custom/DS9FX/VandrosMusic2.mp3",
          "DS9FXCombatMusic1" : "sfx/Custom/DS9FX/CombatMusic1.mp3",
          "DS9FXCombatMusic2" : "sfx/Custom/DS9FX/CombatMusic2.mp3",
          "DS9FXCombatMusic3" : "sfx/Custom/DS9FX/CombatMusic3.mp3",
          "DS9FXCombatMusic4" : "sfx/Custom/DS9FX/CombatMusic4.mp3",
          "DS9FXCombatMusic5" : "sfx/Custom/DS9FX/CombatMusic5.mp3",
          "DS9FXCombatMusic6" : "sfx/Custom/DS9FX/CombatMusic6.mp3",
          "DS9FXCombatMusic7" : "sfx/Custom/DS9FX/CombatMusic7.mp3",
          "DS9FXQonosMusic1" : "sfx/Custom/DS9FX/QonosMusic1.mp3",
          "DS9FXQonosMusic2" : "sfx/Custom/DS9FX/QonosMusic2.mp3",
          "DS9FXQonosMusic3" : "sfx/Custom/DS9FX/QonosMusic3.mp3",
          "DS9FXCardassiaMusic1" : "sfx/Custom/DS9FX/CardassiaMusic1.mp3",
          "DS9FXCardassiaMusic2" : "sfx/Custom/DS9FX/CardassiaMusic2.mp3",  
          "DS9FXTrivasMusic1" : "sfx/Custom/DS9FX/TrivasMusic1.mp3",
          "DS9FXTrivasMusic2" : "sfx/Custom/DS9FX/TrivasMusic2.mp3",           
          "DS9FXChintokaMusic1" : "sfx/Custom/DS9FX/ChintokaMusic1.mp3",
          "DS9FXChintokaMusic2" : "sfx/Custom/DS9FX/ChintokaMusic2.mp3",
          "DS9FXVelaMusic1" : "sfx/Custom/DS9FX/VelaMusic1.mp3",
          "DS9FXVelaMusic2" : "sfx/Custom/DS9FX/VelaMusic2.mp3",          
          "DS9FXFoundersMusic1" : "sfx/Custom/DS9FX/FoundersMusic1.mp3",
          "DS9FXFoundersMusic2" : "sfx/Custom/DS9FX/FoundersMusic2.mp3",
          "DS9FXFoundersMusic3" : "sfx/Custom/DS9FX/FoundersMusic3.mp3"}

def GetMusic():
    global dMusic
    return dMusic