# Do not Edit this file, Hyperdrive uses it to store data

Hyperdrive1 = 0.0
Hyperdrive2 = 0.0
Hyperdrive3 = 0.0
Hyperdrive4 = 0.0
Hyperdrive5 = 0.0
Hyperdrive6 = 0.0
Hyperdrive7 = 0.0
Hyperdrive8 = 0.0
Hyperdrive9 = 0.0
Hyperdrive10 = 0.0
Hyperdrive11 = 0.0
Hyperdrive12 = 0.0
Hyperdrive13 = 0.0
Hyperdrive14 = 0.0
Hyperdrive15 = 0.0
Hyperdrive16 = 0.0
Hyperdrive17 = 0.0
Hyperdrive18 = 0.0
Hyperdrive19 = 0.0
Hyperdrive20 = 0.0

